(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;else root.FlowboardSchedule=api})(typeof globalThis!=='undefined'?globalThis:this,function(){
  const DAY=86400000,SCALE_PX={day:36,week:12,month:4};
  function parseDay(value){if(!/^\d{4}-\d{2}-\d{2}$/.test(value||''))return null;const [year,month,day]=value.split('-').map(Number),time=Date.UTC(year,month-1,day),date=new Date(time);return date.getUTCFullYear()===year&&date.getUTCMonth()===month-1&&date.getUTCDate()===day?time:null}
  function iso(time){return new Date(time).toISOString().slice(0,10)}
  function addDays(value,days){const time=parseDay(value);return time===null?null:iso(time+days*DAY)}
  function diffDays(start,end){const left=parseDay(start),right=parseDay(end);return left===null||right===null?null:Math.round((right-left)/DAY)}
  function layout(tasks,bounds,scale){const px=SCALE_PX[scale]||SCALE_PX.week,start=parseDay(bounds?.start);if(start===null)return[];return tasks.map(task=>({...task,left:diffDays(bounds.start,task.start)*px,width:Math.max(px,(diffDays(task.start,task.end)+1)*px)}))}
  function ticks(bounds,scale){const start=parseDay(bounds?.start),end=parseDay(bounds?.end);if(start===null||end===null)return[];const step=scale==='day'?1:scale==='week'?7:30,result=[];for(let time=start,index=0;time<=end&&result.length<400;time+=step*DAY,index++)result.push({date:iso(time),left:index*step*(SCALE_PX[scale]||12)});return result}
  function criticalPath(tasks,edges){const nodes=new Map(tasks.map(item=>[item.id,item])),incoming=new Map(tasks.map(item=>[item.id,[]])),outgoing=new Map(tasks.map(item=>[item.id,[]]));for(const edge of edges){if(nodes.has(edge.predecessor_id)&&nodes.has(edge.successor_id)){incoming.get(edge.successor_id).push(edge.predecessor_id);outgoing.get(edge.predecessor_id).push(edge.successor_id)}}const indegree=new Map([...incoming].map(([id,list])=>[id,list.length])),queue=[...indegree].filter(([,count])=>!count).map(([id])=>id).sort((a,b)=>a-b),order=[];while(queue.length){const id=queue.shift();order.push(id);for(const next of outgoing.get(id).slice().sort((a,b)=>a-b)){indegree.set(next,indegree.get(next)-1);if(!indegree.get(next)){queue.push(next);queue.sort((a,b)=>a-b)}}}if(order.length!==nodes.size)return{blocked:true,task_ids:[]};const distance=new Map(),previous=new Map();for(const id of order){const duration=nodes.get(id).duration_days||1,best=incoming.get(id).map(parent=>[distance.get(parent)+duration,parent]).sort((a,b)=>b[0]-a[0]||a[1]-b[1])[0];distance.set(id,best?best[0]:duration);if(best)previous.set(id,best[1])}if(!distance.size)return{blocked:false,task_ids:[],duration_days:0};let current=[...distance].sort((a,b)=>b[1]-a[1]||a[0]-b[0])[0][0],path=[];while(nodes.has(current)){path.unshift(current);current=previous.get(current)}return{blocked:false,task_ids:path,duration_days:Math.max(...distance.values())}}
  return{DAY,SCALE_PX,parseDay,iso,addDays,diffDays,layout,ticks,criticalPath};
});
