(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;else root.FlowboardTimeline=api})(typeof globalThis!=='undefined'?globalThis:this,function(){
  const stages=['创意','设计','开发','测试','量产','应用迭代'];
  const stageTokens=Object.freeze({'创意':'idea','设计':'design','开发':'develop','测试':'test','量产':'production','应用迭代':'iteration'});
  const stageClass=stage=>'stage-'+(stageTokens[stage]||'idea');
  const esc=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
  const DAY=86400000;
  const iso=value=>new Date(value+'T00:00:00Z');
  const addDays=(value,days)=>new Date(iso(value).getTime()+days*DAY).toISOString().slice(0,10);
  const compareNodes=(a,b)=>a.date.localeCompare(b.date)||a.name.localeCompare(b.name,undefined,{numeric:true})||a.id-b.id;
  function editorState(project){return {original:JSON.parse(JSON.stringify(project)),project:JSON.parse(JSON.stringify(project)),draft:new Map(),sort:'date',showIntervals:false,armed:null,dirty:false,dragging:false,nextTempId:-1,lastBatchId:null}}
  function ordered(project,sort='date'){const rank=new Map(stages.map((stage,index)=>[stage,index]));return (project.nodes||[]).slice().sort((a,b)=>sort==='stage'?(rank.get(a.stage)-rank.get(b.stage)||compareNodes(a,b)):compareNodes(a,b))}
  function setDraft(state,nodeId,set,meta={}){const previous=state.draft.get(nodeId)||{node_id:nodeId,set:{}};state.draft.set(nodeId,{...previous,set:{...previous.set,...set},...meta});state.dirty=true}
  function toggleDone(state,nodeId,done){const node=state.project.nodes.find(item=>item.id===nodeId);if(!node)return;node.done_at=done?true:null;node.status=done?'已完成':(node.date<(state.project.server_today||shanghaiToday())?'进行中':'未开始');if(nodeId<0){const change=state.draft.get(nodeId);if(change?.create){change.create.done_at=done;state.dirty=true}return}setDraft(state,nodeId,{done_at:done})}
  function createNode(state,values){const id=state.nextTempId--;const node={id,...values,done_at:null,status:'未开始',remark:values.remark||''};state.project.nodes.push(node);state.draft.set(id,{create:{track:node.track,stage:node.stage,name:node.name,date:node.date,remark:node.remark}});state.dirty=true;return node}
  function removeNode(state,nodeId){const index=state.project.nodes.findIndex(item=>item.id===nodeId);if(index<0)return false;state.project.nodes.splice(index,1);if(nodeId<0)state.draft.delete(nodeId);else state.draft.set(nodeId,{node_id:nodeId,remove:true});state.dirty=state.draft.size>0;return true}
  function updateNode(state,nodeId,field,value){const node=state.project.nodes.find(item=>Number(item.id)===Number(nodeId));if(!node)return false;if(field==='done_at'){toggleDone(state,Number(nodeId),Boolean(value));return true}node[field]=value;if(Number(nodeId)<0){const change=state.draft.get(Number(nodeId));if(!change?.create||field==='interval_days')return false;change.create[field]=value;state.dirty=true;return true}if(field==='track'){const previous=state.draft.get(Number(nodeId));if(previous?.set&&Object.prototype.hasOwnProperty.call(previous.set,'interval_days'))delete previous.set.interval_days}setDraft(state,Number(nodeId),{[field]:value},{mode:'cascade'});return true}
  function batchRequest(state,{triggerSource='editor'}={}){const changes=[...state.draft.values()].map(change=>change.create?{create:change.create}:change.remove?{node_id:change.node_id,remove:true}:{node_id:change.node_id,set:change.set});const metadata=[...state.draft.values()].find(change=>change.mode)||{},defaultMode=triggerSource==='drag'?'single':'cascade';return {project_id:state.project.project_id,base_version:state.original.version,trigger_source:triggerSource,details:{mode:metadata.mode||defaultMode,magnet:metadata.magnet||'standard',zoom_band:metadata.zoom_band||'±10d×8',historical_correction:[...state.draft.values()].some(change=>change.historical_correction)},changes}}
  function moveNode(state,nodeId,targetDate,mode){const node=state.project.nodes.find(item=>item.id===nodeId);if(!node)return null;const chain=state.project.nodes.filter(item=>item.track===node.track).slice().sort(compareNodes),index=chain.findIndex(item=>item.id===nodeId),before=chain[index-1],after=chain[index+1];let date=targetDate;if(before&&date<before.date)date=before.date;if(mode==='single'&&after&&date>after.date)date=after.date;const delta=Math.round((iso(date)-iso(node.date))/DAY);node.date=date;setDraft(state,nodeId,{date},{mode,magnet:'standard',zoom_band:'±10d×8',historical_correction:Boolean(node.done_at)});if(mode==='cascade'&&delta){for(const later of chain.slice(index+1)){later.date=addDays(later.date,delta);setDraft(state,later.id,{date:later.date},{mode,magnet:'standard',zoom_band:'±10d×8',cascaded:true})}}return date}
  function discard(state){const ui={sort:state.sort,showIntervals:state.showIntervals,lastBatchId:state.lastBatchId},fresh=editorState(state.original);Object.assign(fresh,ui);Object.assign(state,fresh);return state}
  function bounds(projects){const dates=projects.flatMap(project=>project.nodes||[]).map(node=>node.date).filter(Boolean);const min=dates.length?dates.reduce((a,b)=>a<b?a:b):null;const max=dates.length?dates.reduce((a,b)=>a>b?a:b):null;return {min,max}}
  function shanghaiToday(){try{return new Intl.DateTimeFormat('sv-SE',{timeZone:'Asia/Shanghai'}).format(new Date())}catch(_){return new Date().toISOString().slice(0,10)}}
  function dashboardRange(projects,today=shanghaiToday()){const raw=bounds(projects),min=raw.min&&raw.min<today?raw.min:today,max=raw.max&&raw.max>today?raw.max:today;return {start:addDays(min,-3),end:addDays(max,3),today}}
  function position(date,start,end){const span=Math.max(1,Math.round((iso(end)-iso(start))/DAY));return Math.max(0,Math.min(100,Math.round((iso(date)-iso(start))/DAY)/span*100))}
  function contextMenu(){return `<div class="timeline-context-menu" data-timeline-context hidden role="menu"><button type="button" role="menuitem" data-draft-action="single">拖拽—仅此节点</button><button type="button" role="menuitem" data-draft-action="cascade">拖拽（顺延）</button><button type="button" role="menuitem" data-draft-action="done">已完成</button><button type="button" role="menuitem" data-draft-action="undone">未完成</button></div>`}
  function bindContextController(root,{selector='.timeline-dashboard-node',onAction,onOpen}={}){
    let contextNode=null;
    const menu=root.querySelector('[data-timeline-context]');
    if(!menu)return {hide(){}};
    const closeMenu=()=>{
      contextNode?.element?.classList.remove('is-context-open');
      menu.hidden=true;
      contextNode=null;
    };
    root.querySelectorAll(selector).forEach(node=>node.addEventListener('contextmenu',event=>{
      event.preventDefault();
      closeMenu();
      contextNode={id:Number(node.dataset.nodeId),projectId:Number(node.dataset.projectId||root.dataset.timelineProject||0),element:node};
      node.classList.add('is-context-open');
      menu.querySelectorAll('[data-draft-action]').forEach(button=>button.disabled=false);
      onOpen?.(contextNode,menu);
      menu.hidden=false;
      const flipUp=event.clientY+menu.offsetHeight>window.innerHeight-8;
      const clampX=Math.max(8,Math.min(event.clientX,window.innerWidth-menu.offsetWidth-8));
      menu.style.left=clampX+'px';
      menu.style.top=(flipUp?Math.max(8,event.clientY-menu.offsetHeight):event.clientY)+'px';
    }));
    menu.addEventListener('mousedown',event=>event.stopPropagation());
    menu.addEventListener('click',event=>{
      const button=event.target.closest('[data-draft-action]'),action=button?.dataset.draftAction;
      if(!action||button.disabled||!contextNode)return;
      event.stopPropagation();
      const selected=contextNode;
      closeMenu();
      onAction?.(action,selected);
    });
    document.addEventListener('click',event=>{if(!menu.hidden&&!event.target.closest('[data-timeline-context]'))closeMenu()},{signal:root.__timelineAbort?.signal});
    document.addEventListener('keydown',event=>{if(event.key==='Escape'&&!menu.hidden)closeMenu()},{signal:root.__timelineAbort?.signal});
    return {hide:closeMenu};
  }
  function projectTabs(mode,{write=true,project=null,canArchive=false,canUnarchive=false}={}){
    const archiveAction=canArchive?`<button type="button" class="danger" data-timeline-archive="${project.project_id}">归档项目</button>`:canUnarchive?`<button type="button" data-timeline-unarchive="${project.project_id}">取消归档</button>`:'';
    const menu=archiveAction?`<details class="tl-project-menu"><summary aria-label="项目操作">•••</summary><div>${archiveAction}</div></details>`:'';
    return `<div class="timeline-project-tabs"><nav aria-label="项目页签"><button type="button" class="back" data-timeline-mode-target="home">← 我的工作</button><button type="button" class="${mode==='single'?'on':''}" data-timeline-mode-target="single" aria-pressed="${mode==='single'}">单项目仪表盘</button><button type="button" class="${mode==='editor'?'on':''}" data-timeline-mode-target="editor" aria-pressed="${mode==='editor'}">时间表编辑器</button><button type="button" disabled>审计 · 预留</button></nav><div class="timeline-project-tab-actions"><button type="button" data-timeline-mode-target="all">全项目仪表盘</button>${write&&!project?.archived_at?'<label class="timeline-file-button">导入 Excel<input type="file" accept=".xlsx,.csv" data-timeline-import-file></label><button type="button" data-timeline-export>导出 Excel</button>':''}${menu}</div></div>`;
  }
  function editorIntervals(project){const result=new Map();for(const track of ['main','parallel']){const chain=(project.nodes||[]).filter(node=>node.track===track).slice().sort(compareNodes);chain.forEach((node,index)=>result.set(Number(node.id),index?Math.round((iso(node.date)-iso(chain[index-1].date))/DAY):null))}return result}
  function renderEditor(project,options={}){
    const state=options.state,sort=state?.sort||'date',nodes=ordered(project,sort),draftCount=state?.draft?.size||0,editable=options.editable!==false,showIntervals=Boolean(state?.showIntervals),intervals=editorIntervals(project),today=project.server_today||shanghaiToday();
    const stageOptions=value=>stages.map(stage=>`<option value="${stage}" ${stage===value?'selected':''}>${stage}</option>`).join('');
    const rows=nodes.map((node,index)=>{
      const draft=state?.draft?.get(Number(node.id)),draftSet=draft?.set||{},trackChanged=Object.prototype.hasOwnProperty.call(draftSet,'track'),computed=intervals.get(Number(node.id)),interval=Object.prototype.hasOwnProperty.call(draftSet,'interval_days')?draftSet.interval_days:computed,nonDone=node.status&&node.status!=='已完成'?node.status:(node.date<today?'进行中':'未开始'),intervalEditable=editable&&Number(node.id)>0&&computed!==null&&!trackChanged,rowDraft=state?.draft?.has(Number(node.id)),disabled=editable?'':'disabled';
      return `<tr class="${node.track==='parallel'?'is-parallel ':''}${rowDraft?'is-draft':''}" data-editor-row="${node.id}" data-node-date="${esc(node.date)}"><td class="timeline-sheet-rownum">${index+1}</td><td class="timeline-sheet-stage ${stageClass(node.stage)}"><i></i><select data-editor-field="stage" data-node-id="${node.id}" aria-label="${esc(node.name)}的项目阶段" ${disabled}>${stageOptions(node.stage)}</select></td><td class="timeline-sheet-track"><select data-editor-field="track" data-node-id="${node.id}" aria-label="${esc(node.name)}的轨道" ${disabled}><option value="main" ${node.track==='main'?'selected':''}>主线</option><option value="parallel" ${node.track==='parallel'?'selected':''}>并行</option></select></td><td><input class="timeline-sheet-name" data-editor-field="name" data-node-id="${node.id}" value="${esc(node.name)}" maxlength="500" required aria-label="项目节点" ${disabled}></td><td><input type="date" data-editor-field="date" data-node-id="${node.id}" value="${esc(node.date)}" required aria-label="${esc(node.name)}的日期" ${disabled}></td><td class="timeline-sheet-interval" data-interval-column ${showIntervals?'':'hidden'}>${computed===null?'—':`<input type="number" data-editor-field="interval_days" data-node-id="${node.id}" value="${esc(interval??'')}" min="0" max="3650" step="1" aria-label="${esc(node.name)}距同轨前一节点的间隔天数" ${intervalEditable?'':'disabled'}>`}</td><td><select data-editor-field="done_at" data-node-id="${node.id}" aria-label="${esc(node.name)}的状态" ${disabled}><option value="false" ${node.done_at?'':'selected'}>${esc(nonDone)}</option><option value="true" ${node.done_at?'selected':''}>已完成</option></select></td><td><input class="timeline-sheet-remark" data-editor-field="remark" data-node-id="${node.id}" value="${esc(node.remark||'')}" maxlength="500" aria-label="${esc(node.name)}的备注" ${disabled}></td><td class="timeline-sheet-row-actions">${editable?`<button type="button" data-timeline-remove-node="${node.id}" aria-label="删除节点 ${esc(node.name)}">删除</button>`:'—'}</td></tr>`;
    }).join('');
    const writeActions=editable?`<button type="button" data-timeline-add>＋ 新增节点</button>${options.admin?'<button type="button" data-timeline-correct>纠正初始日期</button>':''}<button type="button" data-timeline-undo ${state?.lastBatchId?'':'disabled'}>撤销上次提交</button><button type="button" class="danger" data-timeline-discard ${draftCount?'':'disabled'}>放弃更改</button><button type="button" class="primary" data-timeline-submit ${draftCount?'':'disabled'}>保存（触发计算＋顺延）</button>`:`<span class="timeline-sheet-readonly">${project.archived_at?'已归档 · 只读（取消归档后可编辑）':'只读：只有项目创建者或工作区管理员可修改'}</span>`;
    return `<section class="timeline-editor timeline-sheet-editor" data-timeline-project="${project.project_id}">${projectTabs('editor',{write:options.write!==false,project,canArchive:options.canArchive,canUnarchive:options.canUnarchive})}<header class="timeline-sheet-head"><div><p class="timeline-eyebrow">PROJECT · 时间管理</p><h2>时间表编辑器</h2><p class="timeline-summary">一行一个节点；用轨道区分主线/并行。两条轨道各自计算间隔与顺延，互不影响。</p></div><span class="timeline-sheet-project">项目：${esc(project.name)}</span></header><div class="timeline-sheet-toolbar"><div><button type="button" data-timeline-sort-toggle aria-pressed="${sort==='stage'}">↕ 排序：${sort==='date'?'按日期':'按六大阶段'}</button><label class="timeline-gap-toggle"><input type="checkbox" data-timeline-gap-toggle ${showIntervals?'checked':''}>显示时间间隔</label><button type="button" data-timeline-review>轻量复盘</button></div><div class="timeline-editor-actions">${writeActions}<span data-timeline-draft-count>${draftCount} 项草稿</span></div></div><div class="timeline-sheet-wrap"><table class="timeline-sheet"><thead><tr><th>#</th><th>项目阶段</th><th>轨道</th><th>项目节点</th><th>日期</th><th data-interval-column ${showIntervals?'':'hidden'}>时间间隔（天）</th><th>状态</th><th>备注</th><th>操作</th></tr></thead><tbody>${rows||'<tr><td colspan="9" class="timeline-sheet-empty">暂无节点；点击“新增节点”开始录入。</td></tr>'}</tbody></table></div><div class="timeline-sheet-legend"><span><i class="stage-idea"></i>创意</span><span><i class="stage-design"></i>设计</span><span><i class="stage-develop"></i>开发</span><span><i class="stage-test"></i>测试</span><span><i class="stage-production"></i>量产</span><span><i class="stage-iteration"></i>应用迭代</span><span>蓝色行标 = 并行轨道</span><span>间隔 = 距同轨上一节点</span></div><div class="timeline-review" data-timeline-review-panel hidden></div></section>`;
  }
  function bindEditor(root,state,{render,onDirty,onSubmit,onAdd,onUndo,onCorrect,onReview,editable=true}={}){
    const updateDraftUi=nodeId=>{const count=state.draft.size;root.querySelector('[data-timeline-draft-count]')?.replaceChildren(document.createTextNode(`${count} 项草稿`));const submit=root.querySelector('[data-timeline-submit]'),discardButton=root.querySelector('[data-timeline-discard]');if(submit)submit.disabled=!count;if(discardButton)discardButton.disabled=!count;if(nodeId!==undefined)root.querySelector(`[data-editor-row="${nodeId}"]`)?.classList.add('is-draft');onDirty?.(state.dirty)};
    root.querySelector('[data-timeline-sort-toggle]')?.addEventListener('click',()=>{state.sort=state.sort==='date'?'stage':'date';render?.()});
    root.querySelector('[data-timeline-gap-toggle]')?.addEventListener('change',event=>{state.showIntervals=event.target.checked;root.querySelectorAll('[data-interval-column]').forEach(cell=>cell.hidden=!state.showIntervals)});
    if(editable)root.querySelectorAll('[data-editor-field]').forEach(input=>input.addEventListener('change',()=>{if(!input.checkValidity()){input.setAttribute('aria-invalid','true');return}input.removeAttribute('aria-invalid');const nodeId=Number(input.dataset.nodeId),field=input.dataset.editorField,value=field==='done_at'?input.value==='true':field==='interval_days'?Number(input.value):input.value;updateNode(state,nodeId,field,value);if(field==='track'){const row=input.closest('[data-editor-row]');row?.classList.toggle('is-parallel',value==='parallel');const interval=row?.querySelector('[data-editor-field="interval_days"]');if(interval)interval.disabled=true}if(field==='stage'){const cell=input.closest('.timeline-sheet-stage');cell.className=`timeline-sheet-stage ${stageClass(value)}`}updateDraftUi(nodeId)}));
    root.querySelector('[data-timeline-discard]')?.addEventListener('click',()=>{discard(state);render?.()});
    root.querySelectorAll('[data-timeline-remove-node]').forEach(button=>button.addEventListener('click',()=>{removeNode(state,Number(button.dataset.timelineRemoveNode));render?.()}));
    root.querySelector('[data-timeline-submit]')?.addEventListener('click',()=>onSubmit?.());
    root.querySelector('[data-timeline-add]')?.addEventListener('click',()=>onAdd?.());
    root.querySelector('[data-timeline-undo]')?.addEventListener('click',()=>onUndo?.());
    root.querySelector('[data-timeline-correct]')?.addEventListener('click',()=>onCorrect?.());
    root.querySelector('[data-timeline-review]')?.addEventListener('click',()=>onReview?.());
  }
  function monthTicks(start,end){
    const first=iso(start),last=iso(end),cursor=new Date(Date.UTC(first.getUTCFullYear(),first.getUTCMonth()+1,1)),ticks=[];
    while(cursor<last){
      const date=cursor.toISOString().slice(0,10),month=cursor.getUTCMonth()+1;
      ticks.push({date,label:`${month}月`,major:(month-1)%3===0});
      cursor.setUTCMonth(cursor.getUTCMonth()+1);
    }
    return ticks;
  }
  function portfolioRange(projects,today=shanghaiToday()){
    const raw=bounds(projects),min=raw.min||today,max=raw.max||today;
    return {start:addDays(min,-30),end:addDays(max,30),today};
  }
  function spanDays(start,end){return Math.max(1,Math.round((iso(end)-iso(start))/DAY))}
  function clampPortfolioViewport(range,viewport={}){
    viewport=viewport||{};
    const fullDays=spanDays(range.start,range.end),minimum=Math.min(14,fullDays),days=Math.max(minimum,Math.min(fullDays,Number(viewport.days)||fullDays)),half=days*DAY/2,start=iso(range.start).getTime(),end=iso(range.end).getTime(),fallback=start+(end-start)/2,raw=viewport.center?iso(viewport.center).getTime():fallback,center=Math.max(start+half,Math.min(end-half,raw));
    return {center:new Date(center).toISOString().slice(0,10),days,scrollTop:Math.max(0,Number(viewport.scrollTop)||0)};
  }
  function calendarGroups(start,end){
    const a=iso(start).getTime(),b=iso(end).getTime(),first=iso(start),cursor=new Date(Date.UTC(first.getUTCFullYear(),first.getUTCMonth(),1)),months=[];
    while(cursor.getTime()<b){const next=new Date(Date.UTC(cursor.getUTCFullYear(),cursor.getUTCMonth()+1,1)),lo=Math.max(a,cursor.getTime()),hi=Math.min(b,next.getTime()),year=cursor.getUTCFullYear(),month=cursor.getUTCMonth()+1;months.push({year,month,quarter:Math.ceil(month/3),lo,hi});cursor.setUTCMonth(cursor.getUTCMonth()+1)}
    const group=(key,label)=>{const map=new Map();for(const month of months){const id=key(month),entry=map.get(id);if(entry){entry.lo=Math.min(entry.lo,month.lo);entry.hi=Math.max(entry.hi,month.hi)}else map.set(id,{label:label(month),lo:month.lo,hi:month.hi})}return [...map.values()]};
    return {months,years:group(month=>String(month.year),month=>`${month.year} 年`),quarters:group(month=>`${month.year}-Q${month.quarter}`,month=>`Q${month.quarter}`)};
  }
  function dayScale(viewportDays,viewportWidth=760){
    const pixelPerDay=Math.max(.1,Number(viewportWidth||760)/Math.max(1,Number(viewportDays)||1));
    if(pixelPerDay>=30)return {density:'weekday',step:1,label:date=>`${date.getUTCDate()} ${['日','一','二','三','四','五','六'][date.getUTCDay()]}`};
    if(pixelPerDay>=14)return {density:'day',step:1,label:date=>String(date.getUTCDate())};
    const step=Math.max(2,Math.ceil(30/pixelPerDay));
    return {density:'sparse',step,label:date=>`${date.getUTCMonth()+1}/${date.getUTCDate()}`};
  }
  function dayTicks(range,viewportDays,viewportWidth=760,className='timeline-e-day-tick'){
    const span=iso(range.end).getTime()-iso(range.start).getTime(),place=t=>(t-iso(range.start).getTime())/span*100,scale=dayScale(viewportDays,viewportWidth),ticks=[];
    for(let time=Math.ceil(iso(range.start).getTime()/DAY)*DAY;time<=iso(range.end).getTime();time+=scale.step*DAY){const date=new Date(time),end=Math.min(iso(range.end).getTime(),time+scale.step*DAY),width=Math.max(0,(end-time)/span*100),label=scale.label(date),value=new Date(time).toISOString().slice(0,10);ticks.push(`<i class="${className} ${date.getUTCDay()===1?'is-week':''}" data-axis-date="${value}" title="${value} · 星期${['日','一','二','三','四','五','六'][date.getUTCDay()]}" style="left:${place(time)}%;width:${width}%"><b>${label}</b></i>`)}
    return {density:scale.density,html:ticks.join('')};
  }
  function renderPortfolioScale(range,viewportDays,viewportWidth=760){
    const groups=calendarGroups(range.start,range.end),span=iso(range.end).getTime()-iso(range.start).getTime(),place=t=>(t-iso(range.start).getTime())/span*100,blocks=(items,className,copy)=>items.map(item=>`<span class="${className}" style="left:${place(item.lo)}%;width:${(item.hi-item.lo)/span*100}%">${copy(item)}</span>`).join(''),ticks=dayTicks(range,viewportDays,viewportWidth);
    const months=groups.months.map(item=>`<span class="timeline-e-month" data-axis-month="${item.year}-${String(item.month).padStart(2,'0')}" style="left:${place(item.lo)}%;width:${(item.hi-item.lo)/span*100}%"><b>${String(item.month).padStart(2,'0')}</b><span>${item.month}月<small>${item.year}</small></span></span>`).join('');
    return `<div class="timeline-calendar" data-e-calendar aria-label="共享绝对日历，年份、月份和日期分层"><span>${range.start}</span><strong>绝对日历</strong><span>${range.end}</span></div><div class="timeline-e-axis" data-day-density="${ticks.density}"><div class="timeline-e-years">${blocks(groups.years,'timeline-e-year',item=>item.label)}</div><div class="timeline-e-months">${months}</div><div class="timeline-e-days">${ticks.html}</div></div>`;
  }
  function dashboardIntervalGeometry(project,item,nodesById){
    const ids=item.node_ids||[],startId=Number(ids[0]),lastId=Number(ids.at(-1)),segments=project.segments||[];
    const bridge=segments.find(segment=>Number(segment.start_node_id)===lastId),endId=Number(bridge?.end_node_id||lastId);
    const first=nodesById.get(startId)?.date||item.start_date||item.start;
    const last=nodesById.get(endId)?.date||nodesById.get(lastId)?.date||item.end_date||item.end||first;
    return {startId,endId,first,last};
  }
  function denseNodeGroups(nodes,pixelPerDay=Infinity){
    const sorted=nodes.slice().sort(compareNodes),groups=[];
    for(const node of sorted){
      const current=groups.at(-1),previous=current?.at(-1),gap=previous?Math.abs((iso(node.date)-iso(previous.date))/DAY):Infinity;
      if(current&&Number.isFinite(pixelPerDay)&&gap*pixelPerDay<18)current.push(node);else groups.push([node]);
    }
    return groups;
  }
  function renderProjectLanes(source,{start,end,today=shanghaiToday(),expanded=new Set(),state=null,pixelPerDay=Infinity}={}){
    const project=state?.project?.project_id===source.project_id?state.project:source;
    const range=start&&end?{start,end,today}:dashboardRange([project],today),intervals=project.stage_intervals||[],nodes=project.nodes||[],nodesById=new Map(nodes.map(node=>[Number(node.id),node]));
    const nodeDates=nodes.map(node=>node.date).filter(Boolean).sort(),running=nodeDates.length&&nodeDates[0]<=range.today&&nodeDates.at(-1)>=range.today,pastMask=running?`<i class="timeline-past-mask" aria-hidden="true" style="width:${position(range.today,range.start,range.end)}%"></i>`:'';
    const originalById=new Map((state?.original?.nodes||[]).map(node=>[Number(node.id),node]));
    const lanes=['main','parallel'].map(track=>{
      const trackIntervals=intervals.filter(item=>item.track===track),maxRow=Math.max(0,...trackIntervals.map(item=>Number(item.row_index)||0)),key=`${project.project_id}:${track}`,open=expanded.has(key);
      const bars=trackIntervals.map(item=>{
        const overlap=Number(item.row_index)||0,{startId,endId,first,last}=dashboardIntervalGeometry(project,item,nodesById),left=position(first,range.start,range.end),right=position(last,range.start,range.end),width=Math.max(1.5,right-left),narrow=width<5;
        return `<button type="button" class="timeline-stage ${stageClass(item.stage)} ${overlap?'is-overlap':''} ${narrow?'is-narrow':''}" data-stage-interval data-stage="${esc(item.stage)}" data-row-index="${overlap}" data-node-ids="${esc((item.node_ids||[]).join(','))}" data-start-node-id="${startId}" data-end-node-id="${endId}" data-overlap-split="${!open&&overlap?'true':'false'}" aria-label="阶段 ${esc(item.stage)}，${esc(first)} 至 ${esc(last)}" style="left:${left}%;width:${width}%;--row:${open?overlap:0}" title="${esc(first)} → ${esc(last)} · ${esc(item.stage)}"><b>${esc(item.stage)}</b><span>${esc(first)} → ${esc(last)}</span></button>`;
      }).join('');
      const origins=nodes.filter(node=>node.track===track).map(node=>{
        const original=originalById.get(Number(node.id)),changed=original&&original.date!==node.date;
        return changed?`<span class="timeline-dashboard-origin" style="left:${position(original.date,range.start,range.end)}%" title="最近已提交位置 ${esc(original.date)}"></span>`:'';
      }).join('');
      const trackNodes=nodes.filter(node=>node.track===track),groups=denseNodeGroups(trackNodes,pixelPerDay);
      const buttons=groups.map((group,nodeOrder)=>{
        if(group.length>1){
          const middle=new Date(group.reduce((total,node)=>total+iso(node.date).getTime(),0)/group.length).toISOString().slice(0,10),description=group.map(node=>`${node.date} ${node.name}`).join('；');
          return `<span class="timeline-node-cluster" role="img" aria-label="${group.length} 个拥挤节点：${esc(description)}" title="${esc(description)}" style="left:${position(middle,range.start,range.end)}%;z-index:${1000-nodeOrder}"></span>`;
        }
        const node=group[0],action=state?.dashboardContext?.nodeId===Number(node.id)?state.dashboardContext.action:'',draft=state?.draft?.has(Number(node.id)),overdue=!node.done_at&&node.date<range.today;
        return `<button type="button" class="timeline-dashboard-node ${stageClass(node.stage)} ${node.done_at?'is-done':''} ${overdue?'is-overdue':''} ${draft?'is-draft':''} ${state?.armed?.nodeId===Number(node.id)?'is-armed':''} ${action?'is-context-target':''}" data-dashboard-hit-target="node" data-node-id="${node.id}" data-project-id="${project.project_id}" data-node-date="${node.date}" ${action?`data-dashboard-action="${esc(action)}"`:''} aria-label="节点 ${esc(node.name)}，${esc(node.stage)}，${esc(node.date)}；右键操作" style="left:${position(node.date,range.start,range.end)}%;z-index:${1000-nodeOrder}"><i></i><span><b>${esc(node.name)}</b><small>${esc(node.stage)} · ${esc(node.date)}</small></span></button>`;
      }).join('');
      return `<div class="timeline-stage-lane ${open?'is-expanded':''}" data-track="${track}" data-overlap-rows="${maxRow+1}"><div class="timeline-track-label"><strong>${track==='main'?'主线':'并行'}</strong>${maxRow?`<button type="button" data-timeline-expand="${key}" aria-expanded="${open}">${open?'收起重叠':'展开重叠'}</button>`:''}</div><div class="timeline-stage-plot" style="--overlap-rows:${open?maxRow+1:1}">${bars}${origins}${buttons}${pastMask}</div></div>`;
    }).join('');
    return `<div class="timeline-stage-lanes">${lanes}</div>`;
  }
  function renderDashboard(source,{start,end,today=shanghaiToday(),expanded=new Set(),state=null,singleViewport=null,singleViewportWidth=760}={}){
    const project=state?.project?.project_id===source.project_id?state.project:source,range=start&&end?{start,end,today}:dashboardRange([project],today);
    const coloredScale=singleViewport?renderPortfolioScale(range,singleViewport.days,singleViewportWidth):null,dayRuler=!coloredScale&&singleViewport&&Number(singleViewportWidth)/Math.max(1,Number(singleViewport.days))>=8?dayTicks(range,singleViewport.days,singleViewportWidth,'timeline-single-day-tick'):null,ruler=dayRuler?dayRuler.html:monthTicks(range.start,range.end).map(tick=>`<span class="${tick.major?'major':''}" style="left:${position(tick.date,range.start,range.end)}%">${tick.label}</span>`).join(''),density=dayRuler?.density||'month';
    const viewportAttrs=singleViewport?` data-viewport-center="${singleViewport.center}" data-viewport-days="${singleViewport.days}" data-full-days="${spanDays(range.start,range.end)}"`:'';
    return `<section class="timeline-dashboard-detail ${singleViewport?'timeline-single-chart':''}" data-calendar-start="${range.start}" data-calendar-end="${range.end}" data-dashboard-project-id="${project.project_id}"${viewportAttrs}>${coloredScale||`<div class="timeline-calendar" aria-label="共享绝对日历"><span>${range.start}</span><strong>绝对日历</strong><span>${range.end}</span></div><div class="timeline-month-ruler" data-day-density="${density}" aria-hidden="true">${ruler}</div>`}<div class="timeline-today-overlay"><div class="timeline-today-line" style="left:${position(range.today,range.start,range.end)}%" data-today="${range.today}"><span>今天 ${range.today}</span></div></div>${renderProjectLanes(project,{...range,expanded,state})}<div class="timeline-dashboard-loupe" data-dashboard-loupe hidden></div></section>`;
  }
  function riskMarkers(project){const overdue=Number(project.metrics?.overdue_count)||0,week=Number(project.metrics?.this_week_count)||0;return `<div class="timeline-risk-markers" aria-label="项目风险提示">${overdue?`<span class="timeline-risk overdue" title="有逾期未完成节点"><i></i>逾期 ${overdue}</span>`:''}${week?`<span class="timeline-risk this-week" title="本周有未完成节点"><i></i>本周 ${week}</span>`:''}${!overdue&&!week?'<span class="timeline-risk none">无逾期或本周未完成提示</span>':''}</div>`}
  function renderSingle(source,options={}){
    const state=options.state,project=state?.project?.project_id===source.project_id?state.project:source,metrics=project.metrics||{},today=options.today||project.server_today||shanghaiToday(),baseRange=options.start&&options.end?{start:options.start,end:options.end,today}:portfolioRange([project],today),range={...baseRange,today},viewport=clampPortfolioViewport(range,options.singleViewport),visibleStart=addDays(viewport.center,-Math.floor(viewport.days/2)),visibleEnd=addDays(visibleStart,viewport.days),allNodes=project.nodes||[],doneCount=allNodes.filter(node=>node.done_at).length,lastNode=[...allNodes].sort((a,b)=>String(a.date).localeCompare(String(b.date))).at(-1),draftCount=state?.draft?.size||0,editable=options.editable!==false;
    const kpiLine=`<p class="tl-proj-kpi"><i class="dot ${stageClass(metrics.current_stage)}"></i>当前 <b>${esc(metrics.current_stage||'—')}</b> ｜ <b>${allNodes.length}</b> 节点 · <b>${doneCount}</b> 已完成${Number(metrics.overdue_count)?` ｜ <b class="tl-red">${metrics.overdue_count} 逾期</b>`:''} ｜ 临近 <b>${esc(metrics.upcoming?.[0]?`${metrics.upcoming[0].date} ${metrics.upcoming[0].name}`:'—')}</b>${lastNode?` ｜ 收尾 <b>${esc(`${lastNode.date} ${lastNode.name}`)}</b>`:''}</p>`;
    const legend=`<div class="tl-legend" aria-label="时间轴图例"><span><i class="stage-idea"></i>创意</span><span><i class="stage-design"></i>设计</span><span><i class="stage-develop"></i>开发</span><span><i class="stage-test"></i>测试</span><span><i class="stage-production"></i>量产</span><span><i class="stage-iteration"></i>应用迭代</span><span><i class="ring"></i>逾期节点</span><span><b>✓</b> 已完成</span><span>｜ 今天 ${esc(range.today)}</span><span>｜ 阶段分界 ) 形</span></div>`;
    const hint=state?.armed?`已解锁「${esc(allNodes.find(node=>Number(node.id)===state.armed.nodeId)?.name||'节点')}」${state.armed.mode==='cascade'?'（顺延后续）':'（仅此节点）'}：按住左键拖动；尚未写入服务器。`:draftCount?`${draftCount} 项草稿待更新；尚未写入服务器。`:'右键节点选择拖拽模式或完成状态；无默认拖拽档。';
    const controls=editable?`<div class="timeline-dashboard-actions"><span data-dashboard-draft-count>${draftCount} 项草稿</span><button type="button" data-dashboard-undo="${project.project_id}" ${state?.lastBatchId?'':'disabled'}>撤销上次提交</button><button type="button" data-dashboard-discard="${project.project_id}" ${draftCount?'':'disabled'}>放弃更改</button><button type="button" class="primary" data-dashboard-submit="${project.project_id}" ${draftCount?'':'disabled'}>更新日期${draftCount?` <b>${draftCount}</b>`:''}</button></div>`:project.archived_at?'<span class="timeline-archive-readonly">已归档 · 只读</span>':'';
    return `<article class="timeline-project-card" data-dashboard-project="${project.project_id}"><header><div><p>PROJECT · 时间管理</p><h2>${esc(project.name)}</h2><p class="timeline-summary">开始 ${esc(metrics.start_date||'—')} · 当前阶段 ${esc(metrics.current_stage||'—')} · 临近 ${esc(metrics.upcoming?.[0]?.date||'—')}</p>${kpiLine}</div>${riskMarkers(project)}</header>${options.context===false?'':projectTabs('single',{write:options.write!==false,project,canArchive:options.canArchive,canUnarchive:options.canUnarchive})}<p class="timeline-single-caption"><span>完整范围 ${range.start} → ${range.end}</span><strong data-single-visible-range>${visibleStart} → ${visibleEnd} · ${Math.round(viewport.days)} 天</strong><span>滚轮缩放 · 左键横向拖拽</span></p><div class="timeline-dashboard timeline-single-scroll" data-single-scroll>${renderDashboard(project,{...range,expanded:options.expanded||new Set(),state,singleViewport:viewport,singleViewportWidth:options.singleViewportWidth})}</div>${legend}${options.context===false?'':editable?contextMenu():''}<footer class="timeline-dashboard-footer"><p class="timeline-dashboard-hint" data-dashboard-hint>${project.archived_at?'归档期间项目内容只读；取消归档后可继续编辑。':hint}</p>${controls}</footer></article>`;
  }
  function renderAll(projects,filters={}){
    const selected=new Set((filters.project_ids||[]).map(Number)),rank=new Map(stages.map((stage,index)=>[stage,index])),keys={start:project=>project.metrics?.start_date||'9999',stage:project=>rank.get(project.metrics?.current_stage)??99,upcoming:project=>project.metrics?.upcoming?.[0]?.date||project.metrics?.start_date||'9999',overdue:project=>-(Number(project.metrics?.overdue_count)||0)},key=filters.archived?'custom':filters.sort_key||'custom',base=projects.filter(project=>!selected.size||selected.has(project.project_id)).slice(),visible=key==='custom'?base:base.sort((a,b)=>keys[key](a)<keys[key](b)?-1:keys[key](a)>keys[key](b)?1:a.project_id-b.project_id),states=filters.states||new Map(),contextProjects=projects.map(project=>states.get(Number(project.project_id))?.project||project),today=filters.today||contextProjects.find(project=>project.server_today)?.server_today||shanghaiToday(),range=portfolioRange(contextProjects,today),viewport=clampPortfolioViewport(range,filters.viewport),fullDays=spanDays(range.start,range.end),editable=project=>typeof filters.editable==='function'?filters.editable(project):filters.editable!==false,canArchive=project=>typeof filters.canArchive==='function'?filters.canArchive(project):false,canReorder=!filters.archived&&key==='custom'&&!selected.size&&filters.canReorder!==false,pixelPerDay=Math.max(.1,(Number(filters.viewportWidth)||760)/viewport.days);
    const scale=renderPortfolioScale(range,viewport.days,filters.viewportWidth);
    const rows=visible.map(source=>{
      const state=states.get(Number(source.project_id)),project=state?.project?.project_id===source.project_id?state.project:source,metrics=project.metrics||{},draftCount=state?.draft?.size||0,canEdit=!project.archived_at&&editable(source),canArchiveProject=!project.archived_at&&canArchive(source),armedNode=state?.armed?project.nodes?.find(node=>Number(node.id)===state.armed.nodeId):null;
      const hint=state?.armed?`已解锁「${esc(armedNode?.name||'节点')}」${state.armed.mode==='cascade'?'（顺延后续）':'（仅此节点）'}：按住左键拖动；尚未写入服务器。`:draftCount?`${draftCount} 项草稿待更新；尚未写入服务器。`:'右键节点选择拖拽模式或完成状态。';
      const controls=canEdit?`<div class="timeline-dashboard-actions timeline-portfolio-actions"><button type="button" data-dashboard-undo="${project.project_id}" ${state?.lastBatchId?'':'disabled'}>撤销</button><button type="button" data-dashboard-discard="${project.project_id}" ${draftCount?'':'disabled'}>放弃</button><button type="button" class="primary" data-dashboard-submit="${project.project_id}" ${draftCount?'':'disabled'}>更新${draftCount?` ${draftCount}`:''}</button></div>`:`<span class="timeline-portfolio-status">${project.archived_at?'已归档 · 只读':'只读'}</span>`;
      const archiveMenu=canArchiveProject?`<details class="timeline-row-menu"><summary aria-label="${esc(project.name)}项目操作">•••</summary><div><button type="button" class="danger" data-timeline-archive="${project.project_id}">归档项目</button></div></details>`:'';
      return `<article class="timeline-portfolio-project ${project.archived_at?'is-archived':''}" data-dashboard-project="${project.project_id}" data-order-project="${project.project_id}"><div class="timeline-portfolio-meta">${canReorder?'<button type="button" class="tl-order-grip" draggable="true" aria-label="拖拽调整个人顺序" tabindex="-1">⋮⋮</button>':''}<strong>${esc(project.name)}</strong><small>${project.archived_at?`归档于 ${esc(String(project.archived_at).slice(0,16).replace('T',' '))}`:`当前 ${esc(metrics.current_stage||'—')} · 临近 ${esc(metrics.upcoming?.[0]?.date||'—')}`}</small>${riskMarkers(project)}<p class="timeline-dashboard-hint" data-dashboard-hint>${project.archived_at?'归档期间只读；取消归档后可编辑。':hint}</p>${controls}${archiveMenu}</div><div class="timeline-portfolio-lanes">${renderProjectLanes(project,{...range,expanded:filters.expanded||new Set(),state,pixelPerDay})}</div></article>`;
    }).join('');
    const legend=`<div class="tl-legend timeline-portfolio-legend" aria-label="全项目时间轴图例"><span><i class="stage-idea"></i>创意</span><span><i class="stage-design"></i>设计</span><span><i class="stage-develop"></i>开发</span><span><i class="stage-test"></i>测试</span><span><i class="stage-production"></i>量产</span><span><i class="stage-iteration"></i>应用迭代</span><span><i class="ring"></i>逾期节点</span><span><i class="cluster"></i>拥挤节点</span><span><b>✓</b> 已完成</span><span>红色竖线 = 今天 ${esc(range.today)}</span><span>左键拖动时间图 = 移动画布</span></div>`;
    const catalog=filters.tagCatalog||{virtual:[],tags:[]},active=filters.orderContext||{context_type:'all',tag_id:null},tagNav=[...(catalog.virtual||[]).map(tag=>({kind:tag.context_type,id:'',name:tag.name,count:tag.project_count})),...(catalog.tags||[]).map(tag=>({kind:'tag',id:tag.tag_id,name:tag.name,count:tag.project_count}))].map(tag=>`<button type="button" data-timeline-tag-context="${tag.kind}" data-tag-id="${tag.id}" class="${active.context_type===tag.kind&&(tag.kind!=='tag'||Number(active.tag_id)===Number(tag.id))?'active':''}">${esc(tag.name)} <small>${tag.count}</small></button>`).join('');
    const heading=filters.archived?'已归档项目':'全项目仪表盘',orderNote=filters.archived?'<p class="tl-order-note">已归档项目按归档时间倒序显示，不参与普通标签或个人排序。</p>':canReorder?'<p class="tl-order-note">拖动项目名前的把手仅调整你的显示顺序，不影响其他成员。</p>':key!=='custom'?'<p class="tl-order-note">自动排序为只读；切回“我的自定义顺序”后可拖拽。</p>':'<p class="tl-order-note">筛选生效时暂停拖拽，清空筛选后恢复。</p>';
    return `<section class="timeline-all timeline-portfolio-card ${filters.fullscreen?'is-fullscreen':''}" data-shared-calendar="true"><nav class="tl-tag-filter" aria-label="项目标签">${tagNav}</nav><header class="timeline-portfolio-head"><div><p class="timeline-eyebrow">PORTFOLIO · 时间管理</p><h2>${heading}</h2><p class="timeline-summary">${visible.length} 个项目横向对齐同一条绝对日历；每项目固定主线 / 并行两行。</p></div><div class="timeline-portfolio-controls"><label>项目筛选<select multiple data-timeline-filter aria-label="项目筛选">${projects.map(project=>`<option value="${project.project_id}" ${selected.has(project.project_id)?'selected':''}>${esc(project.name)}</option>`).join('')}</select></label><label>排序<select data-timeline-sort-key aria-label="项目排序">${[['custom','我的自定义顺序'],['start','开始日期'],['stage','当前阶段'],['upcoming','临近节点'],['overdue','逾期数量']].map(([value,label])=>`<option value="${value}" ${key===value?'selected':''}>${label}</option>`).join('')}</select></label><div class="timeline-portfolio-view-actions"><button type="button" data-portfolio-fit>适配全部</button><button type="button" data-portfolio-zoom-out aria-label="缩小时间轴">−</button><button type="button" data-portfolio-zoom-in aria-label="放大时间轴">＋</button><button type="button" class="primary" data-portfolio-fullscreen>${filters.fullscreen?'退出全屏':'⛶ 全屏'}</button></div></div></header>${orderNote}<div class="timeline-portfolio-scroll" data-portfolio-scroll><div class="timeline-portfolio-chart" data-calendar-start="${range.start}" data-calendar-end="${range.end}" data-viewport-center="${viewport.center}" data-viewport-days="${viewport.days}" data-full-days="${fullDays}"><div class="timeline-portfolio-axis"><div class="timeline-portfolio-axis-label"><strong>项目</strong><span>主线 / 并行</span></div><div class="timeline-portfolio-axis-detail">${scale}</div></div><div class="timeline-portfolio-today"><div class="timeline-today-line" style="left:${position(range.today,range.start,range.end)}%" data-today="${range.today}"><span>今天 ${range.today}</span></div></div><div class="timeline-portfolio-drag-guides" data-portfolio-drag-guides hidden><i class="origin"></i><i class="corridor"></i><i class="target"></i><b class="target-label"></b></div><div class="timeline-portfolio-projects" data-order-list="all">${rows||'<div class="timeline-empty">没有符合筛选条件的项目。</div>'}</div><div class="timeline-dashboard-loupe" data-dashboard-loupe hidden></div></div></div>${legend}${visible.some(project=>!project.archived_at&&editable(project))?contextMenu():''}</section>`;
  }
  function bindDashboard(root,{filters={},states=new Map(),render,onSubmit,onDiscard,onUndo,onViewportChange,editable=()=>true}={}){
    let drag=null;
    const getState=projectId=>states.get(Number(projectId));
    const labels={single:'拖拽—仅此节点',cascade:'拖拽（顺延）',done:'已完成',undone:'未完成'};
    const portfolio=root.querySelector('.timeline-portfolio-card'),portfolioScroll=root.querySelector('[data-portfolio-scroll]'),portfolioChart=portfolioScroll?.querySelector('.timeline-portfolio-chart');
    let portfolioApi=null;
    if(portfolio&&portfolioScroll&&portfolioChart){
      const start=portfolioChart.dataset.calendarStart,end=portfolioChart.dataset.calendarEnd,fullDays=Number(portfolioChart.dataset.fullDays)||spanDays(start,end),minimum=Math.min(14,fullDays),leftWidth=220,available=Math.max(320,portfolioScroll.clientWidth-leftWidth),days=Math.max(minimum,Math.min(fullDays,Number(portfolioChart.dataset.viewportDays)||fullDays)),plotWidth=available*fullDays/days,chartWidth=leftWidth+plotWidth,rangeLabel=portfolio.querySelector('[data-portfolio-visible-range]');
      if(Math.abs((Number(filters.viewportWidth)||0)-available)>1){filters.viewportWidth=available;if(typeof requestAnimationFrame==='function')requestAnimationFrame(()=>render?.())}
      portfolioChart.style.width=chartWidth+'px';
      const centerTime=iso(portfolioChart.dataset.viewportCenter).getTime(),startTime=iso(start).getTime(),endTime=iso(end).getTime(),centerRatio=(centerTime-startTime)/(endTime-startTime);
      portfolioScroll.scrollLeft=Math.max(0,Math.min(chartWidth-portfolioScroll.clientWidth,centerRatio*plotWidth-available/2));portfolioScroll.scrollTop=Math.max(0,Number(filters.viewport?.scrollTop)||0);
      const sync=(persist=false)=>{const ratio=Math.max(0,Math.min(1,(portfolioScroll.scrollLeft+available/2)/plotWidth)),center=new Date(startTime+ratio*(endTime-startTime)).toISOString().slice(0,10),viewStart=addDays(center,-Math.floor(days/2)),viewEnd=addDays(viewStart,days);filters.viewport={center,days,scrollTop:Math.max(0,Math.round(portfolioScroll.scrollTop))};if(rangeLabel)rangeLabel.textContent=`${viewStart} → ${viewEnd} · ${Math.round(days)} 天`;if(persist)onViewportChange?.(filters.viewport)};
      portfolioApi={scroll:portfolioScroll,chart:portfolioChart,start,end,fullDays,days,plotWidth,available,sync};sync(false);
      let pan=null,scrollTimer=0;
      const excluded=target=>{if(target.closest('.timeline-dashboard-node,.timeline-portfolio-meta,.timeline-portfolio-axis-label,input,select,a,[data-timeline-context]'))return true;const control=target.closest('button');return Boolean(control&&!control.classList.contains('timeline-stage'))};
      portfolioScroll.addEventListener('pointerdown',event=>{if(event.button!==0||excluded(event.target))return;pan={id:event.pointerId,x:event.clientX,y:event.clientY,left:portfolioScroll.scrollLeft,top:portfolioScroll.scrollTop,moved:false};portfolioScroll.setPointerCapture?.(event.pointerId);event.preventDefault()});
      portfolioScroll.addEventListener('pointermove',event=>{if(!pan||event.pointerId!==pan.id)return;const dx=event.clientX-pan.x,dy=event.clientY-pan.y;if(!pan.moved&&Math.hypot(dx,dy)<4)return;pan.moved=true;portfolio.classList.add('is-panning');portfolioScroll.scrollLeft=pan.left-dx;portfolioScroll.scrollTop=pan.top-dy;sync(false)});
      const finishPan=event=>{if(!pan||event.pointerId!==pan.id)return;portfolioScroll.releasePointerCapture?.(event.pointerId);pan=null;portfolio.classList.remove('is-panning');sync(true)};
      portfolioScroll.addEventListener('pointerup',finishPan);portfolioScroll.addEventListener('pointercancel',finishPan);
      portfolioScroll.addEventListener('scroll',()=>{clearTimeout(scrollTimer);scrollTimer=setTimeout(()=>sync(true),140)},{passive:true});
      const setViewport=(nextDays,anchorRatio=.5,anchorTime=null)=>{clearTimeout(scrollTimer);const clamped=Math.max(minimum,Math.min(fullDays,nextDays)),currentCenter=filters.viewport?.center||portfolioChart.dataset.viewportCenter,currentStart=iso(addDays(currentCenter,-Math.floor(days/2))).getTime(),anchor=anchorTime??currentStart+days*DAY*anchorRatio,center=new Date(anchor+(0.5-anchorRatio)*clamped*DAY).toISOString().slice(0,10);filters.viewport={center,days:clamped,scrollTop:portfolioScroll.scrollTop};onViewportChange?.(filters.viewport);render?.()};
      portfolioScroll.addEventListener('wheel',event=>{if(event.shiftKey)return;event.preventDefault();const rect=portfolioScroll.getBoundingClientRect(),ratio=Math.max(0,Math.min(1,(event.clientX-rect.left-leftWidth)/available)),currentCenter=filters.viewport?.center||portfolioChart.dataset.viewportCenter,currentStart=iso(addDays(currentCenter,-Math.floor(days/2))).getTime(),anchor=currentStart+days*DAY*ratio;setViewport(days*(event.deltaY>0?1.16:.86),ratio,anchor)},{passive:false});
      portfolio.querySelector('[data-portfolio-zoom-in]')?.addEventListener('click',()=>setViewport(days*.72));
      portfolio.querySelector('[data-portfolio-zoom-out]')?.addEventListener('click',()=>setViewport(days*1.4));
      portfolio.querySelector('[data-portfolio-fit]')?.addEventListener('click',()=>{clearTimeout(scrollTimer);filters.viewport={center:new Date((startTime+endTime)/2).toISOString().slice(0,10),days:fullDays,scrollTop:0};onViewportChange?.(filters.viewport);render?.()});
      portfolio.querySelector('[data-portfolio-fullscreen]')?.addEventListener('click',()=>{filters.fullscreen=!filters.fullscreen;render?.()});
    }
    const singleScroll=root.querySelector('[data-single-scroll]'),singleChart=singleScroll?.querySelector('.timeline-single-chart');
    if(singleScroll&&singleChart){
      const start=singleChart.dataset.calendarStart,end=singleChart.dataset.calendarEnd,fullDays=Number(singleChart.dataset.fullDays)||spanDays(start,end),minimum=Math.min(14,fullDays),leftWidth=114,available=Math.max(320,singleScroll.clientWidth-leftWidth),days=Math.max(minimum,Math.min(fullDays,Number(singleChart.dataset.viewportDays)||fullDays)),plotWidth=available*fullDays/days,chartWidth=leftWidth+plotWidth,rangeLabel=root.querySelector('[data-single-visible-range]'),startTime=iso(start).getTime(),endTime=iso(end).getTime();
      if(Math.abs((Number(filters.singleViewportWidth)||0)-available)>1){filters.singleViewportWidth=available;if(typeof requestAnimationFrame==='function')requestAnimationFrame(()=>render?.())}
      singleChart.style.width=chartWidth+'px';
      const centerTime=iso(singleChart.dataset.viewportCenter).getTime(),centerRatio=(centerTime-startTime)/(endTime-startTime);
      singleScroll.scrollLeft=Math.max(0,Math.min(chartWidth-singleScroll.clientWidth,centerRatio*plotWidth-available/2));
      const sync=()=>{const ratio=Math.max(0,Math.min(1,(singleScroll.scrollLeft+available/2)/plotWidth)),center=new Date(startTime+ratio*(endTime-startTime)).toISOString().slice(0,10),viewStart=addDays(center,-Math.floor(days/2)),viewEnd=addDays(viewStart,days);filters.singleViewport={center,days};if(rangeLabel)rangeLabel.textContent=`${viewStart} → ${viewEnd} · ${Math.round(days)} 天`};
      sync();
      let pan=null;
      const excluded=target=>{if(target.closest('.timeline-dashboard-node,.timeline-node-cluster,.timeline-track-label,input,select,a,summary,[data-timeline-context]'))return true;const control=target.closest('button');return Boolean(control&&!control.classList.contains('timeline-stage'))};
      singleScroll.addEventListener('pointerdown',event=>{if(event.button!==0||excluded(event.target))return;pan={id:event.pointerId,x:event.clientX,left:singleScroll.scrollLeft,moved:false};singleScroll.setPointerCapture?.(event.pointerId);event.preventDefault()});
      singleScroll.addEventListener('pointermove',event=>{if(!pan||event.pointerId!==pan.id)return;const dx=event.clientX-pan.x;if(!pan.moved&&Math.abs(dx)<4)return;pan.moved=true;singleScroll.classList.add('is-panning');singleScroll.scrollLeft=pan.left-dx;sync()});
      const finishPan=event=>{if(!pan||event.pointerId!==pan.id)return;singleScroll.releasePointerCapture?.(event.pointerId);pan=null;singleScroll.classList.remove('is-panning');sync()};
      singleScroll.addEventListener('pointerup',finishPan);singleScroll.addEventListener('pointercancel',finishPan);singleScroll.addEventListener('scroll',sync,{passive:true});
      const setViewport=(nextDays,anchorRatio=.5,anchorTime=null)=>{const clamped=Math.max(minimum,Math.min(fullDays,nextDays)),currentCenter=filters.singleViewport?.center||singleChart.dataset.viewportCenter,currentStart=iso(addDays(currentCenter,-Math.floor(days/2))).getTime(),anchor=anchorTime??currentStart+days*DAY*anchorRatio,center=new Date(anchor+(0.5-anchorRatio)*clamped*DAY).toISOString().slice(0,10);filters.singleViewport={center,days:clamped};render?.()};
      singleScroll.addEventListener('wheel',event=>{if(event.shiftKey)return;event.preventDefault();const rect=singleScroll.getBoundingClientRect(),ratio=Math.max(0,Math.min(1,(event.clientX-rect.left-leftWidth)/available)),currentCenter=filters.singleViewport?.center||singleChart.dataset.viewportCenter,currentStart=iso(addDays(currentCenter,-Math.floor(days/2))).getTime(),anchor=currentStart+days*DAY*ratio;setViewport(days*(event.deltaY>0?1.16:.86),ratio,anchor)},{passive:false});
    }
    root.querySelector('[data-timeline-filter]')?.addEventListener('change',event=>{filters.project_ids=[...event.target.selectedOptions].map(option=>Number(option.value));render?.()});
    root.querySelector('[data-timeline-sort-key]')?.addEventListener('change',event=>{filters.sort_key=event.target.value;render?.()});
    root.querySelectorAll('[data-timeline-expand]').forEach(button=>button.addEventListener('click',()=>{filters.expanded=filters.expanded||new Set();filters.expanded.has(button.dataset.timelineExpand)?filters.expanded.delete(button.dataset.timelineExpand):filters.expanded.add(button.dataset.timelineExpand);render?.()}));
    bindContextController(root,{selector:'.timeline-dashboard-node',onOpen:(context,menu)=>{
      const state=getState(context.projectId),node=state?.project?.nodes.find(item=>Number(item.id)===context.id),allowed=editable(context.projectId);
      menu.querySelectorAll('[data-draft-action]').forEach(button=>button.disabled=!allowed);
      if(node&&allowed)menu.querySelector(`[data-draft-action="${node.done_at?'done':'undone'}"]`).disabled=true;
    },onAction:(action,context)=>{
      const state=getState(context.projectId);if(!state||!editable(context.projectId))return;
      state.dashboardContext={nodeId:context.id,action};
      if(action==='done'||action==='undone'){
        toggleDone(state,context.id,action==='done');state.armed=null;render?.();return;
      }
      state.armed={nodeId:context.id,mode:action};
      root.querySelectorAll('.timeline-dashboard-node.is-armed').forEach(node=>node.classList.remove('is-armed'));
      context.element.classList.add('is-armed','is-context-target');context.element.dataset.dashboardAction=action;
      const hint=context.element.closest('[data-dashboard-project]')?.querySelector('[data-dashboard-hint]');
      if(hint)hint.textContent=`节点 ${context.id}：已选择「${labels[action]}」；按住左键拖动，尚未写入服务器。`;
    }});
    let edgeDelay=0,edgeFrame=0,edgeDirection=0,lastDragPointer=null;
    const stopEdgePan=()=>{clearTimeout(edgeDelay);cancelAnimationFrame(edgeFrame);edgeDelay=0;edgeFrame=0;edgeDirection=0};
    const beginEdgePan=direction=>{if(!drag?.portfolioScroll||direction===edgeDirection)return;stopEdgePan();if(!direction)return;edgeDirection=direction;edgeDelay=setTimeout(()=>{const tick=()=>{if(!drag?.portfolioScroll||!edgeDirection)return;const scroll=drag.portfolioScroll,before=scroll.scrollLeft;scroll.scrollLeft+=edgeDirection*9;drag.syncViewport?.(false);if(scroll.scrollLeft===before){stopEdgePan();return}previewDrag(lastDragPointer||{clientX:drag.startX},true);edgeFrame=requestAnimationFrame(tick)};tick()},350)};
    const previewDrag=(event,fromEdge=false)=>{
      if(!drag)return;
      lastDragPointer={clientX:event.clientX};
      if(drag.portfolioScroll&&!fromEdge){const rect=drag.portfolioScroll.getBoundingClientRect(),margin=54,direction=event.clientX<rect.left+220+margin?-1:event.clientX>rect.right-margin?1:0;beginEdgePan(direction)}
      const scrollShift=drag.portfolioScroll?drag.portfolioScroll.scrollLeft-drag.startScrollLeft:0,rawDelta=Math.round((event.clientX-drag.startX+scrollShift)/drag.pxPerDay),candidate=addDays(drag.startDate,rawDelta),target=candidate<drag.minDate?drag.minDate:candidate>drag.maxDate?drag.maxDate:candidate,delta=Math.round((iso(target)-iso(drag.startDate))/DAY);
      drag.targetDate=target;drag.previewDates=new Map(drag.snapshotDates);
      if(drag.mode==='cascade')drag.chain.slice(drag.index).forEach(node=>drag.previewDates.set(Number(node.id),addDays(drag.snapshotDates.get(Number(node.id)),delta)));
      else drag.previewDates.set(drag.nodeId,target);
      root.querySelectorAll(`.timeline-dashboard-node[data-project-id="${drag.projectId}"]`).forEach(node=>{const date=drag.previewDates.get(Number(node.dataset.nodeId));if(date){node.style.left=position(date,drag.range.start,drag.range.end)+'%';node.classList.toggle('is-dragging',Number(node.dataset.nodeId)===drag.nodeId);}});
      drag.projectRoot.querySelectorAll('[data-stage-interval]').forEach(bar=>{const first=drag.previewDates.get(Number(bar.dataset.startNodeId)),last=drag.previewDates.get(Number(bar.dataset.endNodeId));if(!first||!last)return;const left=position(first,drag.range.start,drag.range.end),right=position(last,drag.range.start,drag.range.end);bar.style.left=left+'%';bar.style.width=Math.max(1.5,right-left)+'%';});
      const committed=drag.committedDate,diff=Math.round((iso(target)-iso(committed))/DAY);
      if(drag.guides){const origin=position(drag.startDate,drag.range.start,drag.range.end),destination=position(target,drag.range.start,drag.range.end),guide=drag.guides;guide.hidden=false;guide.querySelector('.origin').style.left=origin+'%';guide.querySelector('.target').style.left=destination+'%';const corridor=guide.querySelector('.corridor');corridor.style.left=Math.min(origin,destination)+'%';corridor.style.width=Math.abs(destination-origin)+'%';const label=guide.querySelector('.target-label');label.style.left=destination+'%';label.textContent=`${target}  ${diff>=0?'+':''}${diff} 天`;drag.surface.querySelectorAll('.timeline-e-month').forEach(cell=>cell.classList.toggle('is-target',cell.dataset.axisMonth===target.slice(0,7)));const dayLayer=drag.surface.querySelector('.timeline-e-days');dayLayer?.querySelectorAll('.is-target').forEach(tick=>{if(tick.dataset.dynamic==='1')tick.remove();else tick.classList.remove('is-target')});let tick=dayLayer?.querySelector(`[data-axis-date="${target}"]`);if(!tick&&dayLayer){dayLayer.insertAdjacentHTML('beforeend',`<i class="timeline-e-day-tick is-target" data-dynamic="1" data-axis-date="${target}" style="left:${destination}%"><b>${target.slice(5)}</b></i>`)}else tick?.classList.add('is-target')}
      else if(drag.loupe){const ticks=[];for(let offset=-10;offset<=10;offset++){const date=addDays(target,offset),classes=[date===drag.range.today?'today':'',date===drag.minDate||date===drag.maxDate?'boundary':''].filter(Boolean).join(' ');ticks.push(`<i class="${classes}"><b>${date.slice(8)}</b><small>${offset===0?'当前':''}</small></i>`)}const loupe=drag.loupe;loupe.innerHTML=`<div class="timeline-loupe-head"><b>${esc(committed)} → ${esc(target)}</b><span>${diff>=0?'+':''}${diff} 天</span></div><div class="timeline-loupe-scale">${ticks.join('')}</div>`;loupe.hidden=false;const surfaceRect=drag.surface.getBoundingClientRect(),width=loupe.offsetWidth||520,left=Math.max(12,Math.min(surfaceRect.width-width-12,event.clientX-surfaceRect.left-width/2));loupe.style.left=left+'px';loupe.style.top=Math.max(8,drag.plotRect.top-surfaceRect.top-loupe.offsetHeight-10)+'px'}
    };
    const endDrag=(commit=true)=>{
      if(!drag)return;
      const active=drag,state=active.state,target=active.targetDate||active.startDate;
      stopEdgePan();active.syncViewport?.(true);
      document.body.classList.remove('timeline-dragging');
      if(commit&&target!==active.startDate)moveNode(state,active.nodeId,target,active.mode);
      state.dashboardContext={nodeId:active.nodeId,action:active.mode};state.armed=null;drag=null;render?.();
    };
    root.querySelectorAll('.timeline-dashboard-node').forEach(node=>node.addEventListener('mousedown',event=>{
      if(event.button!==0)return;
      const projectId=Number(node.dataset.projectId),state=getState(projectId);
      if(!state?.armed||state.armed.nodeId!==Number(node.dataset.nodeId)||!editable(projectId))return;
      event.preventDefault();
      const projectRoot=node.closest('[data-dashboard-project]'),surface=node.closest('[data-calendar-start][data-calendar-end]'),plot=node.closest('.timeline-stage-plot'),range={start:surface.dataset.calendarStart,end:surface.dataset.calendarEnd,today:surface.querySelector('.timeline-today-line').dataset.today},span=Math.max(1,Math.round((iso(range.end)-iso(range.start))/DAY)),chain=state.project.nodes.filter(item=>item.track===state.project.nodes.find(item=>Number(item.id)===Number(node.dataset.nodeId))?.track).slice().sort(compareNodes),index=chain.findIndex(item=>Number(item.id)===Number(node.dataset.nodeId)),startDate=node.dataset.nodeDate,before=chain[index-1],after=chain[index+1],tailOffset=chain.length?Math.round((iso(chain.at(-1).date)-iso(startDate))/DAY):0,minDate=before?.date||range.start,maxDate=state.armed.mode==='single'?(after?.date||range.end):addDays(range.end,-Math.max(0,tailOffset)),plotRect=plot.getBoundingClientRect(),original=state.original.nodes.find(item=>Number(item.id)===Number(node.dataset.nodeId)),canvasScroll=surface.closest('[data-portfolio-scroll]');
      drag={projectId,nodeId:Number(node.dataset.nodeId),mode:state.armed.mode,state,projectRoot,surface,plotRect,loupe:canvasScroll?null:surface.querySelector('[data-dashboard-loupe]'),guides:canvasScroll?surface.querySelector('[data-portfolio-drag-guides]'):null,portfolioScroll:canvasScroll,startScrollLeft:canvasScroll?.scrollLeft||0,syncViewport:canvasScroll?portfolioApi?.sync:null,range,chain,index,startX:event.clientX,startDate,committedDate:original?.date||startDate,minDate,maxDate:maxDate<minDate?minDate:maxDate,pxPerDay:Math.max(.5,plotRect.width/span),snapshotDates:new Map(state.project.nodes.map(item=>[Number(item.id),item.date])),targetDate:startDate};
      document.body.classList.add('timeline-dragging');node.classList.add('is-dragging');previewDrag(event);
    }));
    document.addEventListener('mousemove',previewDrag,{signal:root.__timelineAbort?.signal});
    document.addEventListener('mouseup',()=>endDrag(true),{signal:root.__timelineAbort?.signal});
    document.addEventListener('keydown',event=>{if(event.key!=='Escape')return;if(drag)endDrag(false);else if(filters.fullscreen){filters.fullscreen=false;render?.()}else{for(const state of states.values())state.armed=null;render?.()}},{signal:root.__timelineAbort?.signal});
    root.querySelectorAll('[data-dashboard-submit]').forEach(button=>button.addEventListener('click',()=>onSubmit?.(Number(button.dataset.dashboardSubmit))));
    root.querySelectorAll('[data-dashboard-discard]').forEach(button=>button.addEventListener('click',()=>{const projectId=Number(button.dataset.dashboardDiscard),state=getState(projectId);if(onDiscard)onDiscard(projectId);else if(state){discard(state);render?.()}}));
    root.querySelectorAll('[data-dashboard-undo]').forEach(button=>button.addEventListener('click',()=>onUndo?.(Number(button.dataset.dashboardUndo))));
  }
  function renderTransfer(transfer={},{starters=true}={}){const preview=transfer.preview,error=transfer.error,detailRows=error?.details?.rows,rows=Array.isArray(detailRows)?detailRows:error?.details?.row?[error.details]:[],projects=preview?.projects||[],warnings=preview?.warnings||[],starterControls=starters?`<label class="timeline-file-button">选择文件<input type="file" accept=".xlsx,.csv" data-timeline-import-file></label><button type="button" data-timeline-export ${transfer.busy?'disabled':''}>导出工作区时间表</button>`:'';return `<section class="timeline-transfer" aria-label="项目时间表 Excel 导入导出"><header><div><h3>Excel / CSV 导入导出</h3><p>严格八列表头；导入只新建项目，先预览，确认无错后再提交。</p></div><div class="timeline-transfer-actions">${starterControls}<button type="button" data-timeline-import-commit ${!preview||error||transfer.busy||transfer.committed?'disabled':''}>提交预览批次</button></div></header><div class="timeline-transfer-state" aria-live="polite">${transfer.busy?'<p class="timeline-transfer-busy">正在校验文件…</p>':''}${transfer.filename?`<p data-timeline-import-filename>已选择：${esc(transfer.filename)}</p>`:''}${preview?`<article class="timeline-import-preview" data-timeline-preview-id="${preview.batch_id}"><strong>预览通过：${preview.row_count} 行 · ${projects.length} 个项目</strong><ul class="timeline-project-summary">${projects.map(project=>`<li>${esc(project.name)}：${project.node_count} 个节点</li>`).join('')}</ul>${warnings.length?`<ul class="timeline-import-warnings">${warnings.map(warning=>`<li>提示：${esc(warning)}</li>`).join('')}</ul>`:''}</article>`:''}${error?`<article class="timeline-import-error" data-timeline-import-error="${esc(error.code||'IMPORT_ERROR')}"><strong>${esc(error.code||'IMPORT_ERROR')}：${esc(error.message)}</strong>${rows.length?`<table><thead><tr><th>行</th><th>项目/列</th><th>问题</th></tr></thead><tbody>${rows.map(row=>`<tr data-import-error-row="${esc(row.row||'')}"><td>${esc(row.row||'—')}</td><td>${esc(row.project||row.header||row.column||'—')}</td><td>${esc(row.message||error.message)}</td></tr>`).join('')}</tbody></table>`:''}</article>`:''}${transfer.committed?`<p class="timeline-import-success">导入完成：${transfer.committed.projects} 个项目、${transfer.committed.nodes} 个节点。</p>`:''}${transfer.exportReady?`<article class="timeline-export-ready"><strong>服务端文件校验通过</strong><span>${esc(transfer.exportReady.filename)} · SHA-256 ${esc(transfer.exportReady.sha256)}</span><a data-timeline-download href="${esc(transfer.exportReady.url)}" download="${esc(transfer.exportReady.filename)}">下载已校验文件</a></article>`:''}</div></section>`}
  function feedKind(kind,changes=[]){const fields=new Set(changes.map(row=>row.field));if(fields.has('created'))return '新增节点';if(fields.has('deleted'))return '删除节点';return ({direct_edit:'更新节点',status_toggle:'切换状态',undo:'撤销提交',initial_correction:'纠正初始日期',import:'导入项目'})[kind]||kind||'更新'}
  function feedTime(stamp){const text=String(stamp||''),date=text.slice(0,10),clock=text.slice(11,16),today=shanghaiToday();if(date===today)return `今天 ${clock}`;if(date===addDays(today,-1))return `昨天 ${clock}`;return text.length>=16?text.slice(5,16).replace('T',' '):text}
  function feedValue(value){if(value===null||value===undefined)return '';if(typeof value==='object')return '';const text=String(value).trim();return /^[\[{]/.test(text)?'':text}
  function feedRowSummary(row){const node=String(row?.node_name||'节点'),field=String(row?.field||''),oldValue=feedValue(row?.old_value),newValue=feedValue(row?.new_value),labels={created:'新建节点',deleted:'删除节点',date:'调整日期',initial_date:'纠正初始日期',status:'切换状态',done_at:'切换状态',stage:'调整阶段',track:'调整轨道',name:'重命名节点',remark:'更新备注'},action=labels[field]||'更新节点',change=oldValue||newValue?`：${oldValue||'—'} → ${newValue||'—'}`:'';return `${node} · ${action}${change}`}
  function feedRows(review,currentUser,scope){const limit=scope==='mine'?6:20,flat=(review||[]).flatMap(project=>(project.batches||[]).map(batch=>({project:project.name,batch}))).filter(item=>scope!=='mine'||item.batch.actor?.name===currentUser).sort((a,b)=>String(b.batch.created_at||'').localeCompare(String(a.batch.created_at||''))||b.batch.batch_id-a.batch.batch_id).slice(0,limit);if(!flat.length)return '<p class="tl-feed-empty">暂无动态</p>';return flat.map(item=>{const batch=item.batch,actor=batch.actor?.name||'—',changes=batch.change_rows||[],summary=changes.length?`${feedRowSummary(changes[0])}${changes.length>1?`（共 ${changes.length} 项）`:''}`:'';return `<article class="tl-feed-item"><span class="tl-feed-avatar" aria-hidden="true">${esc(actor.slice(0,1))}</span><span class="tl-feed-copy"><span><b>${esc(actor)}</b> ${esc(feedKind(batch.change_kind,changes))} · ${esc(item.project)}</span>${summary?`<small title="${esc(summary)}">${esc(summary)}</small>`:''}</span><time>${esc(feedTime(batch.created_at))}</time></article>`}).join('')}
  function ownedBy(project,person){return !!person&&(project.created_by===person.id||project.created_by===person.name)}
  function homeStats(projects,members,currentUser,review){const mine=projects.filter(project=>ownedBy(project,currentUser)),sum=list=>list.reduce((total,project)=>total+(Number(project.metrics?.overdue_count)||0),0),today=shanghaiToday(),flat=(review||[]).flatMap(project=>project.batches||[]),day=batch=>String(batch.created_at||'').slice(0,10);return {mine:mine.length,myOverdue:sum(mine),team:projects.length,overdue:sum(projects),members:(members||[]).length,todayFeed:flat.filter(batch=>day(batch)===today).length,yesterdayFeed:flat.filter(batch=>day(batch)===addDays(today,-1)).length}}
  function renderHomeView(projects,{admin=false,write=false,members=[],currentUser=null,review=null,mineOrder=null}={}){
    const stats=homeStats(projects,members,currentUser,review),mineRaw=projects.filter(project=>ownedBy(project,currentUser)),byId=new Map(mineRaw.map(project=>[Number(project.project_id),project])),mine=mineOrder?.project_ids?[...mineOrder.project_ids.map(id=>byId.get(Number(id))).filter(Boolean),...mineRaw.filter(project=>!mineOrder.project_ids.map(Number).includes(Number(project.project_id)))]:mineRaw;
    const row=project=>{const metrics=project.metrics||{},count=(project.nodes||[]).length,stage=count?metrics.current_stage||project.nodes[0]?.stage:'',upcoming=metrics.upcoming?.[0]?.date,overdue=Number(metrics.overdue_count)||0,status=count?`${esc(stage||'未开始')}${overdue?` · <b class="tl-red">逾期 ${overdue}</b>`:''}${upcoming?` · 临近 ${esc(upcoming.slice(5).replace('-','/'))}`:''}`:'未开始 · 待录入首个节点';return `<article class="tl-prow" data-project-choice="${project.project_id}" data-order-project="${project.project_id}"><button type="button" class="tl-order-grip" draggable="true" aria-label="拖拽调整我的顺序" tabindex="-1">⋮⋮</button><button type="button" class="tl-prow-main" data-timeline-open="single" data-project-id="${project.project_id}"><i class="tl-prow-dot ${count?stageClass(stage):'is-empty'}"></i><strong>${esc(project.name)}</strong><span class="tl-prow-meta">${status}</span>${overdue?`<span class="tl-risk-chip">逾期 ${overdue}</span>`:''}<span class="tl-prow-go" aria-hidden="true">›</span></button><span class="tl-prow-actions"><button type="button" data-timeline-open="editor" data-project-id="${project.project_id}">编辑</button>${admin?`<button type="button" class="timeline-delete" data-timeline-delete="${project.project_id}" data-project-version="${project.version}">删除</button>`:''}</span></article>`};
    const strip=member=>{const owned=projects.filter(project=>ownedBy(project,member)),isMe=Boolean(currentUser&&member.id===currentUser.id),pills=owned.map((project,index)=>{const metrics=project.metrics||{},overdue=Number(metrics.overdue_count)||0,upcoming=metrics.upcoming?.[0]?.date,locked=!admin&&!ownedBy(project,currentUser);return `<button type="button" class="tl-pill ${stageClass(metrics.current_stage)}" data-timeline-member-open="${project.project_id}"${index>=10?' data-member-extra hidden':''}><i class="dot"></i><b>${esc(project.name)}</b><small>${overdue?`逾期 ${overdue}`:esc(metrics.current_stage||'未开始')}${upcoming?` · 临近 ${esc(upcoming.slice(5).replace('-','/'))}`:''}</small>${locked?'<span class="tl-lock">🔒 只读</span>':''}</button>`}).join(''),more=owned.length>10?`<button type="button" class="tl-member-more" data-timeline-member-toggle="${esc(member.id)}" aria-expanded="false">显示全部（剩余 ${owned.length-10} 个）</button>`:'';return `<div class="tl-mrow"><div class="tl-member-head"><span class="tl-mavatar" aria-hidden="true">${esc(String(member.name||'?').slice(0,1))}</span><span><b>${esc(member.name||'')}${isMe?'（我）':''}</b><small>${isMe&&admin?'admin':'member'} · ${owned.length} 个项目</small></span></div><span class="tl-mpills">${owned.length?`${pills}${more}`:'<span class="tl-mnone">暂无负责项目</span>'}</span></div>`};
    const actions=write?`<div class="tl-home-actions"><label class="tl-home-import">⇪ 导入 Excel<input type="file" accept=".xlsx,.csv" data-timeline-import-file></label><button type="button" class="tl-home-export" data-timeline-export>导出 Excel</button><form data-timeline-create><input name="name" maxlength="200" required aria-label="项目名称" placeholder="项目名称"><button type="submit">＋ 新建项目</button></form></div>`:'';
    return `<div class="tl-home"><header class="tl-home-head"><div><p>信息总览 · 登录默认页</p><h1>我的工作</h1><small>今天 ${shanghaiToday()} · 点击任意数字或项目行可下钻</small></div>${actions}</header><div class="tl-kpis"><button type="button" class="tl-kpi" data-timeline-kpi="mine"><small>我的项目</small><span><b>${stats.mine}</b>${stats.myOverdue?`<em class="r">逾期 ${stats.myOverdue}</em>`:''}</span></button><button type="button" class="tl-kpi" data-timeline-kpi="team"><small>团队项目</small><span><b>${stats.team}</b>${stats.overdue?`<em class="r">逾期 ${stats.overdue}</em>`:''}</span></button><button type="button" class="tl-kpi" data-timeline-kpi="members"><small>团队成员</small><span><b>${stats.members}</b></span></button><button type="button" class="tl-kpi" data-timeline-kpi="feed"><small>今日团队动态</small><span><b>${stats.todayFeed}</b>${stats.yesterdayFeed?`<em class="g">昨日 ${stats.yesterdayFeed}</em>`:''}</span></button></div><div class="tl-cols"><div class="tl-maincol"><div class="tl-tabs" role="tablist"><button type="button" class="on" data-timeline-tab="mine">我的项目（${stats.mine}）</button><button type="button" data-timeline-tab="team">团队项目（${stats.team}）</button></div><p class="tl-order-note">拖拽左侧手柄可调整你自己的项目顺序，其他成员不受影响。</p><section class="tl-section" data-timeline-section="mine" data-order-list="mine">${mine.length?mine.map(row).join(''):'<div class="tl-empty">暂无负责项目，可通过上方“新建项目”创建。</div>'}</section><section class="tl-section team" data-timeline-section="team" hidden>${members.length?members.map(strip).join(''):'<div class="tl-empty">暂无成员</div>'}</section><p class="tl-home-note" data-timeline-home-note="mine">整行点击进入项目页（单项目仪表盘 / 时间表编辑器）；日期、间隔、阶段、轨道、节点状态和备注均可在时间表中维护。</p></div><aside class="tl-feed"><h4>最新动态 <small data-timeline-feed-scope>我 · 最近 6 条 · 新在上</small></h4><p class="tl-feed-note">随左侧标签联动：我的项目显示当前用户最近 6 条，团队项目显示全员最近 20 条；最新记录在上。</p><div data-timeline-feed="mine">${feedRows(review,currentUser?.name,'mine')}</div><div data-timeline-feed="team" hidden>${feedRows(review,currentUser?.name,'team')}</div></aside></div></div>`;
  }

  function renderArchived(projects){
    const rows=projects.map(project=>`<article class="tl-archive-row"><strong>${esc(project.name)}</strong>${project.can_unarchive?`<button type="button" data-timeline-unarchive="${project.project_id}">取消归档</button>`:''}</article>`).join('');
    return `<section class="tl-archive-page"><header><div><p>SYSTEM LABEL · 高优先级归档状态</p><h1>已归档</h1><small>归档项目已从普通入口隐藏；取消归档后恢复原标签与个人顺序。</small></div></header><div class="tl-archive-list">${rows||'<div class="tl-empty">暂无已归档项目。</div>'}</div></section>`;
  }

  function renderTags(tagsState={}){
    const catalog=tagsState.catalog||{tags:[],role:'member'},selected=Number(tagsState.selectedId)||null,view=tagsState.membership,active=(catalog.tags||[]).find(tag=>Number(tag.tag_id)===selected),card=(project,included)=>`<article class="tl-tag-project" draggable="true" data-tag-project="${project.project_id}" data-tag-included="${included?'1':'0'}"><span class="tl-order-grip" aria-hidden="true">⋮⋮</span><strong>${esc(project.name)}</strong><small>${included?'已加入':'未加入'}</small></article>`,tags=(catalog.tags||[]).map(tag=>`<button type="button" class="tl-tag-row ${Number(tag.tag_id)===selected?'active':''}" data-tag-select="${tag.tag_id}"><span>${esc(tag.name)}</span><small>${tag.project_count}</small></button>`).join('');
    return `<section class="tl-tags"><header class="tl-tags-head"><div><p>SHARED LABELS · 全团队共同维护</p><h1>标签</h1><small>标签名称和项目归属会影响所有成员；此页拖拽不改变任何人的项目顺序。</small></div><div class="tl-tag-head-actions">${tagsState.undo?'<button type="button" data-tag-undo>撤销上次归属变更</button>':''}<form data-tag-create><input name="name" maxlength="80" required placeholder="新标签名称" aria-label="新标签名称"><button type="submit">＋ 新建标签</button></form></div></header><div class="tl-tags-layout"><aside class="tl-tag-directory"><h3>项目分组标签</h3>${tags||'<p class="tl-empty">还没有标签，先新建一个。</p>'}</aside><main class="tl-tag-workbench">${active&&view?`<header><div><p>当前共享标签</p><h2>${esc(active.name)}</h2><small>横向拖到另一栏后立即保存，项目可同时属于多个标签。</small></div><div class="tl-tag-actions"><button type="button" data-tag-rename="${active.tag_id}" data-tag-version="${active.version}">重命名</button>${catalog.role==='admin'?`<button type="button" class="danger" data-tag-delete="${active.tag_id}" data-tag-version="${active.version}">删除标签</button>`:''}</div></header><div class="tl-tag-columns"><section data-tag-drop="excluded"><h3>未加入 <small>${view.excluded.length}</small></h3><div class="tl-tag-projects">${view.excluded.map(project=>card(project,false)).join('')||'<p class="tl-empty">所有项目都已加入。</p>'}</div></section><section data-tag-drop="included"><h3>已加入 <small>${view.included.length}</small></h3><div class="tl-tag-projects">${view.included.map(project=>card(project,true)).join('')||'<p class="tl-empty">拖项目到这里加入标签。</p>'}</div></section></div>`:'<div class="tl-tag-placeholder"><strong>选择一个标签</strong><p>随后可在“未加入 / 已加入”两栏间拖拽项目。</p></div>'}</main></div></section>`;
  }
  function renderWorkspace(projects,{mode='all',selectedId=null,admin=false,write=false,editor=null,dashboardStates=new Map(),filters={},transfer={},members=[],currentUser='',review=null,tagsState={},mineOrder=null}={}){
    const selected=projects.find(project=>project.project_id===selectedId)||projects[0],empty='<div class="timeline-empty">暂无项目。可先在上方新建项目。</div>',canEdit=project=>Boolean(project&&!project.archived_at&&!project.read_only&&(admin||(write&&(project.created_by===currentUser?.id||project.created_by===currentUser?.name)))),canArchive=project=>Boolean(project?.can_archive),canUnarchive=project=>Boolean(project?.can_unarchive);
    let content=empty;
    if(mode==='home')content=renderHomeView(projects,{admin,write,members,currentUser,review,mineOrder});
    else if(mode==='all')content=renderAll(projects,{...filters,states:dashboardStates,editable:canEdit});
    else if(mode==='archived')content=renderArchived(projects);
    else if(mode==='tags')content=renderTags(tagsState);
    else if(selected)content=mode==='editor'?renderEditor(editor?.project||selected,{state:editor,write,editable:canEdit(selected),admin,canArchive:canArchive(selected),canUnarchive:canUnarchive(selected)}):renderSingle(selected,{expanded:filters.expanded||new Set(),state:dashboardStates.get(Number(selected.project_id)),editable:canEdit(selected),write,singleViewport:filters.singleViewport,singleViewportWidth:filters.singleViewportWidth,canArchive:canArchive(selected),canUnarchive:canUnarchive(selected)});
    const projectMode=['single','editor'].includes(mode),homeMode=['home','tags','archived'].includes(mode),toolbar=projectMode||homeMode?'':`<div class="timeline-toolbar"><nav aria-label="项目时间管理页面"><button type="button" data-timeline-mode-target="home">项目列表</button><button type="button" data-timeline-mode-target="editor" ${selected?'':'disabled'}>时间表编辑器</button><button type="button" data-timeline-mode-target="single" ${selected?'':'disabled'}>单项目仪表盘</button><button type="button" data-timeline-mode-target="all">全项目仪表盘</button></nav>${write?'<form data-timeline-create><label>项目名称 <input name="name" maxlength="200" required></label><button type="submit">新建项目</button></form>':''}</div>`,transferActive=Boolean(transfer.busy||transfer.filename||transfer.preview||transfer.error||transfer.committed||transfer.exportReady);
    return `<section class="timeline-workspace" data-timeline-mode="${esc(mode)}">${toolbar}${write&&transferActive?renderTransfer(transfer,{starters:mode==='all'}):''}<div class="timeline-page" data-timeline-page="${esc(mode)}">${content}</div></section>`;
  }
  return {bounds,dashboardRange,renderEditor,renderSingle,renderAll,renderDashboard,renderTransfer,renderWorkspace,renderTags,renderArchived,stageClass,editorState,ordered,moveNode,toggleDone,createNode,updateNode,removeNode,batchRequest,discard,bindEditor,bindDashboard,bindContextController,addDays};
});
