(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;else root.FlowboardViews=api})(typeof globalThis!=='undefined'?globalThis:this,function(){
  const key=value=>String(value);
  function tasks(groups){return groups.flatMap(group=>group.tasks||[])}
  function tableColumns(view,fields){const byId=new Map(fields.filter(f=>f.is_active).map(f=>[f.id,f]));const order=view?.column_order||['title',...fields.filter(f=>f.is_active).map(f=>f.id)];return order.map(id=>id==='title'?{id:'title',name:'任务'}:byId.get(id)).filter(Boolean)}
  function grid(columns,presentation={}){const widths=presentation.widths||{};return columns.map(c=>`${Math.max(80,Math.min(600,widths[key(c.id)]||(c.id==='title'?250:140)))}px`).join(' ')+' 38px'}
  function kanban(field,items,members){const columns=[{key:'',label:'未设置'}];if(field.field_type==='status')columns.push(...field.options.filter(o=>o.is_active!==false).map(o=>({key:key(o.id),label:o.label,value:o.id})));else columns.push(...members.map(m=>({key:key(m.id),label:m.name,value:m.id})));return columns.map(column=>({...column,tasks:items.filter(task=>key(task.field_values?.[key(field.id)]??'')===column.key).sort((a,b)=>(a.board_order-b.board_order)||(a.id-b.id))}))}
  function iso(date){return `${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}-${String(date.getDate()).padStart(2,'0')}`}
  function monthCells(year,month){const first=new Date(year,month,1),start=new Date(year,month,1-first.getDay());return Array.from({length:42},(_,i)=>{const date=new Date(start);date.setDate(start.getDate()+i);return{iso:iso(date),day:date.getDate(),outside:date.getMonth()!==month}})}
  function calendar(field,items,year,month){const buckets=new Map(monthCells(year,month).map(cell=>[cell.iso,[]])),undated=[],outside=[];items.forEach(task=>{const raw=task.field_values?.[key(field.id)],value=field.field_type==='timeline'?raw?.start:raw;if(typeof value==='string'&&/^\d{4}-\d{2}-\d{2}$/.test(value)){if(buckets.has(value))buckets.get(value).push(task);else outside.push(task)}else undated.push(task)});return{cells:monthCells(year,month).map(cell=>({...cell,tasks:buckets.get(cell.iso)})),undated,outside}}
  function patch(task,field,value){return{version:task.version,field_values:{[field.id]:value??null}}}
  function kanbanPatch(task,boardVersion,field,value,anchorTaskId=null,placement='after'){return{version:task.version,board_version:boardVersion,field_id:field.id,value:value??null,anchor_task_id:anchorTaskId,placement}}
  function controller({api,refresh,lock=()=>{},fail=()=>{}}){return async function mutate(task,field,value){lock(true);try{await api(`/api/tasks/${task.id}`,'PATCH',patch(task,field,value));await refresh()}catch(error){fail(error);await refresh(true)}finally{lock(false)}}}
  function bindDrops(root,{field,columns=[],canWrite,findTask,mutate}){if(!canWrite)return;let dragged=null;root.querySelectorAll('[data-view-task]').forEach(card=>card.ondragstart=()=>{dragged=findTask(+card.dataset.viewTask)});root.querySelectorAll('[data-field-drop],[data-date-drop]').forEach(zone=>{zone.ondragover=event=>event.preventDefault();zone.ondrop=event=>{event.preventDefault();if(!dragged)return;let value=zone.dataset.dateDrop;if(zone.dataset.fieldDrop!==undefined)value=columns.find(item=>item.key===zone.dataset.fieldDrop)?.value??null;const task=dragged;dragged=null;return mutate(task,field,value||null,{anchorTaskId:zone.dataset.anchorTask?+zone.dataset.anchorTask:null,placement:zone.dataset.placement||'after'})}})}
  return{tasks,tableColumns,grid,kanban,monthCells,calendar,patch,kanbanPatch,controller,bindDrops};
});
