(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;else root.FlowboardViewState=api})(typeof globalThis!=='undefined'?globalThis:this,function(){
  function resolve({views=[],effectiveDefaultId=null,activeViewId=null,urlExplicit=false,adHoc=false,blockedLatch=false}){
    if(blockedLatch)return {kind:'blocked',view:null};
    if(adHoc)return {kind:'adhoc',view:null};
    const wanted=activeViewId||(urlExplicit?null:effectiveDefaultId);
    if(!wanted)return {kind:'synthetic',view:null};
    const view=views.find(item=>item.id===wanted);
    return !view||view.blocked?{kind:'blocked',view:null}:{kind:'view',view};
  }
  function fields(allFields,presentation){const active=allFields.filter(field=>field.is_active);if(!presentation)return active;const visible=new Set(presentation.visible_fields||[]),byId=new Map(active.map(field=>[field.id,field]));return (presentation.column_order||[]).filter(id=>id!=='title'&&visible.has(id)).map(id=>byId.get(id)).filter(Boolean)}
  function reset(){return {activeQuery:{version:1,filter:{op:'and',children:[]},sort:[]},activeViewId:null,activePresentation:null,adHocQuery:false,urlViewExplicit:false,blockedLatch:false,viewType:'table',localPresentation:{version:1,widths:{},frozen_columns:[]}}}
  function canAction(view,action){return action==='delete'?Boolean(view?.can_delete):['set-default','unset-default'].includes(action)?Boolean(view?.can_set_default):['update','rename'].includes(action)?Boolean(view?.can_update):true}
  function queryFor(resolution,current){return resolution.kind==='view'?{version:1,filter:resolution.view.filter,sort:resolution.view.sort}:current}
  function transition(current,event,payload={}){const next={...current};if(event==='identity')return reset();if(['search','filter','sort'].includes(event)){next.blockedLatch=false;next.adHocQuery=true;next.urlViewExplicit=false;next.activeViewId=null;next.activePresentation=null}if(event==='view-type'&&!next.blockedLatch){next.adHocQuery=true;next.urlViewExplicit=false;next.activeViewId=null;next.activePresentation=null;next.viewType=payload.viewType;next.localPresentation=payload.presentation}if(event==='select'){next.blockedLatch=false;next.adHocQuery=false;next.activeViewId=payload.id||null;next.urlViewExplicit=Boolean(payload.id);next.activePresentation=null}if(event==='board'){return reset()}if(['create','copy'].includes(event)){next.blockedLatch=false;next.adHocQuery=false;next.activeViewId=payload.id;next.urlViewExplicit=true}if(['delete','clear-default','fallback'].includes(event)){next.blockedLatch=false;next.adHocQuery=false;next.activeViewId=null;next.activePresentation=null;next.urlViewExplicit=false}return next}
  function defaultPresentation(type,fields){if(type==='kanban'){const field=fields.find(f=>f.is_active&&f.system_key==='status')||fields.find(f=>f.is_active&&['status','person'].includes(f.field_type));return field?{version:1,group_field_id:field.id}:null}if(type==='calendar'){const field=fields.find(f=>f.is_active&&f.system_key==='due')||fields.find(f=>f.is_active&&['date','timeline'].includes(f.field_type));return field?{version:1,date_field_id:field.id}:null}if(['timeline','gantt'].includes(type))return{version:1,source:{kind:'fixed'},scale:'week',show_dependencies:type==='gantt',...(type==='gantt'?{show_critical_path:true}:{}),baseline:'disabled'};if(type==='chart')return{version:1,chart_type:'bar',dimension:{kind:'core',key:'status'},metric:{op:'count'},date_bucket:'none',top_n:20,null_policy:'include'};return{version:1,widths:{},frozen_columns:[]}}
  function refreshFailure(status,silent){return status===401?{identityExpired:true,showLogin:true,report:false}:{identityExpired:false,showLogin:false,report:!silent}}
  async function manage(current,action,view,perform){if(!action||action==='unknown')return {state:current,cancelled:true};if(!canAction(view,action))return {state:current,denied:true};try{const result=await perform();const event=['create','copy'].includes(action)?action:['delete','clear-default'].includes(action)?'fallback':null;return {state:event?transition(current,event,{id:result?.id}):current,result}}catch(error){return {state:current,error}}}
  function orderedFields(raw,valid){if(raw===null)return null;const ids=raw.split(',').map(x=>x.trim()).filter(Boolean).map(Number);if(ids.some(id=>!Number.isInteger(id)||!valid.includes(id))||new Set(ids).size!==ids.length)throw Error('字段顺序无效');return ids}
  function chartPresentation(o,current={}){const chartType=o.prompt('图表类型：bar / line / pie / stacked_bar',current.chart_type||'bar');if(!['bar','line','pie','stacked_bar'].includes(chartType))throw Error('图表类型无效');const raw=o.prompt('维度：status / priority / owner_id / due / 动态字段 ID',current.dimension?.kind==='dynamic'?String(current.dimension.id):current.dimension?.key||'status');const core=['status','priority','owner_id','due'].includes(raw),dimension=core?{kind:'core',key:raw}:{kind:'dynamic',id:Number(raw)};if(!core&&!o.fields.some(field=>field.id===dimension.id))throw Error('维度字段无效');const bucket=chartType==='line'?o.prompt('日期分桶：day / week / month',current.date_bucket||'month'):'none';if(!['none','day','week','month'].includes(bucket))throw Error('日期分桶无效');return{version:1,chart_type:chartType,dimension,metric:{op:'count'},date_bucket:bucket,top_n:20,null_policy:'include'}}
  function presentationFor(type,o,current={}){if(type==='chart')return chartPresentation(o,current);if(type==='kanban'){const valid=o.fields.filter(f=>f.is_active&&['status','person'].includes(f.field_type));const id=Number(o.prompt(`Kanban 分组字段：${valid.map(f=>`${f.id}:${f.name}`).join(',')}`,current.group_field_id||valid[0]?.id));if(!valid.some(f=>f.id===id))throw Error('Kanban 字段无效');return{version:1,group_field_id:id}}if(type==='calendar'){const valid=o.fields.filter(f=>f.is_active&&['date','timeline'].includes(f.field_type));const id=Number(o.prompt(`日历日期/时间线字段：${valid.map(f=>`${f.id}:${f.name}`).join(',')}`,current.date_field_id||valid[0]?.id));if(!valid.some(f=>f.id===id))throw Error('日历字段无效');return{version:1,date_field_id:id}}if(['timeline','gantt'].includes(type)){const valid=o.fields.filter(f=>f.is_active&&['date','timeline'].includes(f.field_type));const raw=o.prompt(`排期来源：fixed 或动态字段 ID（${valid.map(f=>`${f.id}:${f.name}`).join(',')}）`,current.source?.kind==='dynamic'?String(current.source.id):'fixed');if(raw!=='fixed'&&!valid.some(f=>String(f.id)===raw))throw Error('排期来源无效');const scale=o.prompt('粒度：day / week / month',current.scale||'week');if(!['day','week','month'].includes(scale))throw Error('排期粒度无效');return{version:1,source:raw==='fixed'?{kind:'fixed'}:{kind:'dynamic',id:Number(raw)},scale,show_dependencies:type==='gantt',...(type==='gantt'?{show_critical_path:true}:{}),baseline:'disabled'}}const widths={...(current.widths||{})};const widthRaw=o.prompt('列宽 JSON（80-600）',JSON.stringify(widths));if(widthRaw===null)throw Error('已取消');const frozenRaw=o.prompt('冻结列（按顺序逗号分隔，例如 title）',(current.frozen_columns||[]).join(','));if(frozenRaw===null)throw Error('已取消');return{version:1,widths:JSON.parse(widthRaw||'{}'),frozen_columns:frozenRaw.split(',').map(x=>x.trim()).filter(Boolean).map(x=>x==='title'?'title':Number(x))}}
  async function runManage(o){const action=o.prompt('视图操作：create / update / rename / set-default / unset-default / copy / delete / clear-default','create');if(!action)return {state:o.current,cancelled:true};const view=o.view,valid=o.fields.filter(f=>f.is_active).map(f=>f.id);return manage(o.current,action,view,async()=>{if(action==='create'){const name=o.prompt('视图名称','我的视图');if(!name?.trim())throw Error('已取消');const scope=o.prompt('范围：personal 或 shared','personal');if(!['personal','shared'].includes(scope))throw Error('视图范围无效');if(scope==='shared'&&o.role==='viewer')throw Object.assign(Error('没有权限创建共享视图'),{denied:true});const type=o.prompt('类型：table / kanban / calendar / timeline / gantt / chart',o.viewType||'table');if(!['table','kanban','calendar','timeline','gantt','chart'].includes(type))throw Error('视图类型无效');const ids=orderedFields(o.prompt(`可见字段 ID（逗号分隔，可排序）：${valid.join(',')}`,valid.join(',')),valid);if(ids===null)throw Error('已取消');return o.api(`/api/boards/${o.boardId}/views`,'POST',{name:name.trim(),scope,view_type:type,filter:o.query.filter,sort:o.query.sort,visible_fields:ids,column_order:['title',...ids],presentation:presentationFor(type,o),is_default:false})}if(action==='clear-default'){await o.api(`/api/boards/${o.boardId}/views/clear-personal-default`,'POST',{});return{}}if(!view)throw Error('请先选择视图');if(action==='copy')return o.api(`/api/views/${view.id}/copy`,'POST',{});if(action==='delete'){await o.api(`/api/views/${view.id}`,'DELETE',{version:view.version});return{}}if(action==='rename'){const name=o.prompt('新名称',view.name);if(!name?.trim())throw Error('已取消');return o.api(`/api/views/${view.id}`,'PATCH',{version:view.version,name:name.trim()})}if(action==='set-default'||action==='unset-default')return o.api(`/api/views/${view.id}`,'PATCH',{version:view.version,is_default:action==='set-default'});if(action==='update'){const ids=orderedFields(o.prompt(`可见字段 ID（逗号分隔，可排序）：${valid.join(',')}`,(view.visible_fields||[]).join(',')),valid);if(ids===null)throw Error('已取消');return o.api(`/api/views/${view.id}`,'PATCH',{version:view.version,filter:o.query.filter,sort:o.query.sort,visible_fields:ids,column_order:['title',...ids],presentation:presentationFor(view.view_type,o,view.presentation)})}throw Error('未知视图操作')})}
  return {resolve,fields,reset,canAction,queryFor,transition,defaultPresentation,refreshFailure,manage,orderedFields,presentationFor,runManage};
});
