const assert=require('assert');const S=require('../view-state.js');let n=0;const check=(value,message)=>{n++;assert.ok(value,message)};
const personal={id:2,blocked:false,visible_fields:[20],column_order:['title',20],can_update:true,can_delete:true};
const shared={id:1,blocked:false,visible_fields:[10],column_order:['title',10],can_update:false,can_delete:false};
check(S.resolve({views:[shared,personal],effectiveDefaultId:2}).view===personal,'personal default');
check(S.resolve({views:[shared,personal],effectiveDefaultId:2,activeViewId:1,urlExplicit:true}).view===shared,'URL wins');
check(S.resolve({views:[],effectiveDefaultId:null}).kind==='synthetic','synthetic');
let latch=true;check(S.resolve({blockedLatch:latch}).kind==='blocked','blocked refresh one');check(S.resolve({blockedLatch:latch}).kind==='blocked','blocked refresh two');
for(const bad of [{id:99},personal])check(S.resolve({views:bad===personal?[{...personal,blocked:true}]:[],activeViewId:bad.id,urlExplicit:true}).kind==='blocked','invalid view');
const reset=S.reset();check(!reset.adHocQuery&&!reset.blockedLatch&&reset.activeViewId===null,'identity reset');
check(reset.viewType==='table'&&reset.localPresentation.version===1,'identity resets local view presentation');
const ordered=S.fields([{id:10,is_active:true},{id:20,is_active:true}],{visible_fields:[20],column_order:['title',20]});check(ordered.map(x=>x.id).join(',')==='20','column presentation');
check(!S.canAction(shared,'update')&&!S.canAction(shared,'delete'),'viewer shared denied');check(S.canAction(personal,'update'),'personal allowed');
personal.filter={field:{kind:'core',key:'title'},operator:'equals',value:'B'};personal.sort=[];const body=S.queryFor({kind:'view',view:personal},{version:1});check(body.filter.value==='B','actual query body');
const blocked={...S.reset(),blockedLatch:true};for(const event of ['search','filter','sort','board','delete','clear-default','fallback'])check(!S.transition(blocked,event).blockedLatch,`${event} unlocks`);for(const event of ['select','create','copy'])check(!S.transition(blocked,event,{id:2}).blockedLatch&&S.transition(blocked,event,{id:2}).activeViewId===2,`${event} selects`);
check(S.transition(blocked,'management').blockedLatch,'unknown management event is no-op');
const tabBlocked=S.transition(blocked,'view-type',{viewType:'kanban',presentation:{version:1,group_field_id:10}});check(tabBlocked.blockedLatch&&tabBlocked.viewType==='table','blocked tab does not unlock or transition');
const prior={...S.reset(),activeQuery:{version:1,filter:{op:'and',children:[{field:{kind:'core',key:'title'},operator:'contains',value:'A'}]},sort:[]}};const tab=S.transition(prior,'view-type',{viewType:'kanban',presentation:{version:1,group_field_id:10}});check(tab.adHocQuery&&tab.viewType==='kanban'&&tab.activeQuery===prior.activeQuery,'tab is explicit ad-hoc transition preserving query');
check(!S.canAction({can_update:true,can_set_default:false},'set-default'),'dedicated default denied');check(S.canAction({can_update:false,can_set_default:true},'set-default'),'dedicated default allowed');
const expired=S.refreshFailure(401,true);check(expired.identityExpired&&expired.showLogin&&!expired.report,'silent 401 boundary');check(!S.refreshFailure(500,true).report,'silent ordinary error');
(async()=>{let calls=0;const fail=async()=>{calls++;throw Error('x')},ok=async()=>{calls++;return{id:7}};for(const action of [null,'unknown']){const r=await S.manage(blocked,action,personal,fail);check(r.state.blockedLatch,`${action} stays blocked`)}const denied=await S.manage(blocked,'set-default',{can_set_default:false},ok);check(denied.denied&&calls===0,'denied no api');const failed=await S.manage(blocked,'create',personal,fail);check(failed.state.blockedLatch&&calls===1,'failure stays blocked');for(const action of ['create','copy']){const r=await S.manage(blocked,action,personal,ok);check(!r.state.blockedLatch&&r.state.activeViewId===7,`${action} commit`)}for(const action of ['delete','clear-default']){const r=await S.manage(blocked,action,personal,ok);check(!r.state.blockedLatch&&r.state.activeViewId===null,`${action} fallback`)}
const fields=[{id:10,is_active:true,field_type:'status'},{id:20,is_active:true,field_type:'date'}],query={filter:{op:'and',children:[]},sort:[]};async function scenario(inputs,role='member',view=null,apiImpl=null){const prompts=[...inputs],requests=[];const api=apiImpl||(async(path,method,payload)=>{requests.push({path,method,payload});return{id:9,version:2}});const outcome=await S.runManage({current:blocked,view,role,boardId:1,fields,query,prompt:()=>prompts.shift(),api});return{outcome,requests}}
let x=await scenario(['create','P','personal','table','20','{}','']);check(x.requests[0].payload.scope==='personal'&&x.requests[0].payload.visible_fields.join(',')==='20','personal create payload');check(x.outcome.state.activeViewId===9,'personal create selects');x=await scenario(['create','S','shared','kanban','20,10','10'],'member');check(x.requests[0].payload.scope==='shared'&&x.requests[0].payload.presentation.group_field_id===10,'shared create payload');x=await scenario(['create','S','shared','table','20'],'viewer');check(x.requests.length===0&&x.outcome.state.blockedLatch,'viewer shared denied');x=await scenario(['update','20,10','{}',''],'member',{...personal,view_type:'table',presentation:{version:1},version:1,visible_fields:[10]});check(x.requests[0].payload.visible_fields.join(',')==='20,10','update ordered columns');x=await scenario([null]);check(x.outcome.cancelled&&x.outcome.state.blockedLatch,'handler cancel');x=await scenario(['create','P','personal','table','20','{}',''],'member',null,async()=>{throw Error('api')});check(x.outcome.error&&x.outcome.state.blockedLatch,'handler api failure');console.log(`view-state assertions: ${n}`)})().catch(error=>{console.error(error);process.exitCode=1});
